function e(a){throw a;}var i=void 0,p=null;function aa(){return function(){}}function ba(a){return function(b){this[a]=b}}function r(a){return function(){return this[a]}}function s(a){return function(){return a}}var t,ca=ca||{},w=this;function x(){}function y(a){a.D=function(){return a.Md||(a.Md=new a)}}
function da(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";else if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(c=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function ea(a){return da(a)=="array"}function fa(a){var b=da(a);return b=="array"||b=="object"&&typeof a.length=="number"}function z(a){return typeof a=="string"}function ga(a){return typeof a=="number"}function ha(a){return da(a)=="function"}function ia(a){a=da(a);return a=="object"||a=="array"||a=="function"}function ja(a){return a[ka]||(a[ka]=++la)}
var ka="closure_uid_"+Math.floor(Math.random()*2147483648).toString(36),la=0;function ma(a,b,c){return a.call.apply(a.bind,arguments)}function na(a,b,c){var d=b||w;if(arguments.length>2){var g=Array.prototype.slice.call(arguments,2);return function(){var b=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(b,g);return a.apply(d,b)}}else return function(){return a.apply(d,arguments)}}
function oa(a,b,c){oa=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?ma:na;return oa.apply(p,arguments)}function pa(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,c);return a.apply(this,b)}}var qa=Date.now||function(){return+new Date};function A(a,b){function c(){}c.prototype=b.prototype;a.a=b.prototype;a.prototype=new c;a.prototype.constructor=a};function ra(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")}function sa(a){if(!ta.test(a))return a;a.indexOf("&")!=-1&&(a=a.replace(va,"&amp;"));a.indexOf("<")!=-1&&(a=a.replace(wa,"&lt;"));a.indexOf(">")!=-1&&(a=a.replace(xa,"&gt;"));a.indexOf('"')!=-1&&(a=a.replace(ya,"&quot;"));return a}var va=/&/g,wa=/</g,xa=/>/g,ya=/\"/g,ta=/[&<>\"]/;
function za(a,b){for(var c=0,d=ra(String(a)).split("."),g=ra(String(b)).split("."),f=Math.max(d.length,g.length),h=0;c==0&&h<f;h++){var j=d[h]||"",k=g[h]||"",l=RegExp("(\\d*)(\\D*)","g"),o=RegExp("(\\d*)(\\D*)","g");do{var m=l.exec(j)||["","",""],n=o.exec(k)||["","",""];if(m[0].length==0&&n[0].length==0)break;c=Aa(m[1].length==0?0:parseInt(m[1],10),n[1].length==0?0:parseInt(n[1],10))||Aa(m[2].length==0,n[2].length==0)||Aa(m[2],n[2])}while(c==0)}return c}
function Aa(a,b){if(a<b)return-1;else if(a>b)return 1;return 0}var Ba={};function Ca(a){return Ba[a]||(Ba[a]=String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()}))};var Da,Ea,Fa,Ga,Ha,Ia,Ja;function La(){return w.navigator?w.navigator.userAgent:p}function Ma(){return w.navigator}Ha=Ga=Fa=Ea=Da=!1;var Na;if(Na=La()){var Oa=Ma();Da=Na.indexOf("Opera")==0;Ea=!Da&&Na.indexOf("MSIE")!=-1;Ga=(Fa=!Da&&Na.indexOf("WebKit")!=-1)&&Na.indexOf("Mobile")!=-1;Ha=!Da&&!Fa&&Oa.product=="Gecko"}var Pa=Da,B=Ea,C=Ha,D=Fa,Qa=Ga,Ra,Sa=Ma();Ra=Sa&&Sa.platform||"";Ia=Ra.indexOf("Mac")!=-1;Ja=Ra.indexOf("Win")!=-1;var Ta=!!Ma()&&(Ma().appVersion||"").indexOf("X11")!=-1,Ua;
a:{var Va="",Wa;if(Pa&&w.opera)var Xa=w.opera.version,Va=typeof Xa=="function"?Xa():Xa;else if(C?Wa=/rv\:([^\);]+)(\)|;)/:B?Wa=/MSIE\s+([^\);]+)(\)|;)/:D&&(Wa=/WebKit\/(\S+)/),Wa)var Ya=Wa.exec(La()),Va=Ya?Ya[1]:"";if(B){var Za,$a=w.document;Za=$a?$a.documentMode:i;if(Za>parseFloat(Va)){Ua=String(Za);break a}}Ua=Va}var ab={};function E(a){return ab[a]||(ab[a]=za(Ua,a)>=0)};function bb(a,b){for(var c in a)b.call(i,a[c],c,a)}function cb(a,b){b in a&&delete a[b]}function db(a,b,c){b in a&&e(Error('The object already contains the key "'+b+'"'));a[b]=c}var eb=["constructor","hasOwnProperty","isPrototypeOf","propertyIsEnumerable","toLocaleString","toString","valueOf"];function fb(a,b){for(var c,d,g=1;g<arguments.length;g++){d=arguments[g];for(c in d)a[c]=d[c];for(var f=0;f<eb.length;f++)c=eb[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function F(a,b){this.x=a!==i?a:0;this.y=b!==i?b:0}F.prototype.hb=function(){return new F(this.x,this.y)};function gb(a,b){return new F(a.x-b.x,a.y-b.y)};function hb(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d}hb.prototype.hb=function(){return new hb(this.top,this.right,this.bottom,this.left)};hb.prototype.contains=function(a){return!this||!a?!1:a instanceof hb?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom};var G=Array.prototype,ib=G.indexOf?function(a,b,c){return G.indexOf.call(a,b,c)}:function(a,b,c){c=c==p?0:c<0?Math.max(0,a.length+c):c;if(z(a))return!z(b)||b.length!=1?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},jb=G.forEach?function(a,b,c){G.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,g=z(a)?a.split(""):a,f=0;f<d;f++)f in g&&b.call(c,g[f],f,a)},kb=G.map?function(a,b,c){return G.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,g=Array(d),f=z(a)?a.split(""):
a,h=0;h<d;h++)h in f&&(g[h]=b.call(c,f[h],h,a));return g},lb=G.every?function(a,b,c){return G.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,g=z(a)?a.split(""):a,f=0;f<d;f++)if(f in g&&!b.call(c,g[f],f,a))return!1;return!0};function mb(a,b){return ib(a,b)>=0}function nb(a,b){var c=ib(a,b);c>=0&&G.splice.call(a,c,1)}function ob(a){return G.concat.apply(G,arguments)}function pb(a){if(ea(a))return ob(a);else{for(var b=[],c=0,d=a.length;c<d;c++)b[c]=a[c];return b}}
function qb(a,b,c,d){G.splice.apply(a,rb(arguments,1))}function rb(a,b,c){return arguments.length<=2?G.slice.call(a,b):G.slice.call(a,b,c)};function H(a,b){this.width=a;this.height=b}H.prototype.hb=function(){return new H(this.width,this.height)};H.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};H.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function I(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d}I.prototype.hb=function(){return new I(this.left,this.top,this.width,this.height)};I.prototype.contains=function(a){return a instanceof I?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};var sb={},tb;function ub(a){return(a=a.className)&&typeof a.split=="function"?a.split(/\s+/):[]}function J(a,b){var c=ub(a),d=rb(arguments,1),g;g=c;for(var f=0,h=0;h<d.length;h++)mb(g,d[h])||(g.push(d[h]),f++);g=f==d.length;a.className=c.join(" ");return g}function vb(a,b){var c=ub(a),d=rb(arguments,1),g;g=c;for(var f=0,h=0;h<g.length;h++)mb(d,g[h])&&(qb(g,h--,1),f++);g=f==d.length;a.className=c.join(" ");return g}
function wb(a,b,c){for(var d=ub(a),g=!1,f=0;f<d.length;f++)d[f]==b&&(qb(d,f--,1),g=!0);if(g)d.push(c),a.className=d.join(" ")};var xb=!B||E("9"),yb=B&&!E("9");function K(a){return a?new zb(L(a)):tb||(tb=new zb)}
function Ab(a,b,c,d){a=d||a;b=b&&b!="*"?b.toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(!D||Bb(document)||E("528"))&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName)if(a=a.getElementsByClassName(c),b){for(var d={},g=0,f=0,h;h=a[f];f++)b==h.nodeName&&(d[g++]=h);d.length=g;return d}else return a;a=a.getElementsByTagName(b||"*");if(c){d={};for(f=g=0;h=a[f];f++)b=h.className,typeof b.split=="function"&&mb(b.split(/\s+/),c)&&(d[g++]=h);d.length=g;return d}else return a}
function Cb(a,b){bb(b,function(b,d){d=="style"?a.style.cssText=b:d=="class"?a.className=b:d=="for"?a.htmlFor=b:d in Db?a.setAttribute(Db[d],b):a[d]=b})}var Db={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",maxlength:"maxLength",type:"type"};
function Eb(a,b,c,d){function g(c){c&&b.appendChild(z(c)?a.createTextNode(c):c)}for(;d<c.length;d++){var f=c[d];if(fa(f)&&!(ia(f)&&f.nodeType>0)){var h;a:{if(f&&typeof f.length=="number")if(ia(f)){h=typeof f.item=="function"||typeof f.item=="string";break a}else if(ha(f)){h=typeof f.item=="function";break a}h=!1}jb(h?pb(f):f,g)}else g(f)}}function Bb(a){return a.compatMode=="CSS1Compat"}function Fb(a,b){Eb(L(a),a,arguments,1)}function Gb(a){for(var b;b=a.firstChild;)a.removeChild(b)}
function Hb(a){a&&a.parentNode&&a.parentNode.removeChild(a)}function Ib(a){for(a=a.firstChild;a&&a.nodeType!=1;)a=a.nextSibling;return a}function Jb(a,b){if(a.contains&&b.nodeType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!="undefined")return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}function L(a){return a.nodeType==9?a:a.ownerDocument||a.document}var Kb={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},Lb={IMG:" ",BR:"\n"};
function Mb(a){var b=a.getAttributeNode("tabindex");return b&&b.specified?(a=a.tabIndex,ga(a)&&a>=0):!1}function Nb(a){if(yb&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];Ob(a,b,!0);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");B||(a=a.replace(/ +/g," "));a!=" "&&(a=a.replace(/^\s*/,""));return a}
function Ob(a,b,c){if(!(a.nodeName in Kb))if(a.nodeType==3)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in Lb)b.push(Lb[a.nodeName]);else for(a=a.firstChild;a;)Ob(a,b,c),a=a.nextSibling}function zb(a){this.k=a||w.document||document}t=zb.prototype;t.o=K;function Pb(a){return a.k}t.b=function(a){return z(a)?this.k.getElementById(a):a};
t.d=function(a,b,c){var d=this.k,g=arguments,f=g[0],h=g[1];if(!xb&&h&&(h.name||h.type)){f=["<",f];h.name&&f.push(' name="',sa(h.name),'"');if(h.type){f.push(' type="',sa(h.type),'"');var j={};fb(j,h);h=j;delete h.type}f.push(">");f=f.join("")}f=d.createElement(f);if(h)z(h)?f.className=h:ea(h)?J.apply(p,[f].concat(h)):Cb(f,h);g.length>2&&Eb(d,f,g,2);return f};t.createElement=function(a){return this.k.createElement(a)};t.createTextNode=function(a){return this.k.createTextNode(a)};
function Qb(a){return Bb(a.k)}function Rb(a){a=!D&&Bb(a.k)?a.k.documentElement:a.k.body;return new F(a.scrollLeft,a.scrollTop)}t.appendChild=function(a,b){a.appendChild(b)};t.Pc=Ib;t.contains=Jb;function M(a,b,c){z(b)?Sb(a,c,b):bb(b,pa(Sb,a))}function Sb(a,b,c){a.style[Ca(c)]=b}function N(a,b){var c=L(a);return c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,p))?c[b]||c.getPropertyValue(b):""}function Tb(a,b){return N(a,b)||(a.currentStyle?a.currentStyle[b]:p)||a.style[b]}function Ub(a,b,c){var d,g=C&&(Ia||Ta)&&E("1.9");b instanceof F?(d=b.x,b=b.y):(d=b,b=c);a.style.left=Vb(d,g);a.style.top=Vb(b,g)}function Wb(a){return new F(a.offsetLeft,a.offsetTop)}
function Xb(a){var b=a.getBoundingClientRect();if(B)a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop;return b}
function Yb(a){if(B)return a.offsetParent;for(var b=L(a),c=Tb(a,"position"),d=c=="fixed"||c=="absolute",a=a.parentNode;a&&a!=b;a=a.parentNode)if(c=Tb(a,"position"),d=d&&c=="static"&&a!=b.documentElement&&a!=b.body,!d&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||c=="fixed"||c=="absolute"))return a;return p}
function Zb(a){for(var b=new hb(0,Infinity,Infinity,0),c=K(a),d=c.k.body,g=!D&&Bb(c.k)?c.k.documentElement:c.k.body,f;a=Yb(a);)if((!B||a.clientWidth!=0)&&(!D||a.clientHeight!=0||a!=d)&&(a.scrollWidth!=a.clientWidth||a.scrollHeight!=a.clientHeight)&&Tb(a,"overflow")!="visible"){var h=$b(a),j;j=a;if(C&&!E("1.9")){var k=parseFloat(N(j,"borderLeftWidth"));if(ac(j)){var l=j.offsetWidth-j.clientWidth-k-parseFloat(N(j,"borderRightWidth"));k+=l}j=new F(k,parseFloat(N(j,"borderTopWidth")))}else j=new F(j.clientLeft,
j.clientTop);h.x+=j.x;h.y+=j.y;b.top=Math.max(b.top,h.y);b.right=Math.min(b.right,h.x+a.clientWidth);b.bottom=Math.min(b.bottom,h.y+a.clientHeight);b.left=Math.max(b.left,h.x);f=f||a!=g}d=g.scrollLeft;g=g.scrollTop;D?(b.left+=d,b.top+=g):(b.left=Math.max(b.left,d),b.top=Math.max(b.top,g));if(!f||D)b.right+=d,b.bottom+=g;c=c.k.parentWindow||c.k.defaultView||window;f=c.document;D&&!E("500")&&!Qa?(typeof c.innerHeight=="undefined"&&(c=window),f=c.innerHeight,a=c.document.documentElement.scrollHeight,
c==c.top&&a<f&&(f-=15),c=new H(c.innerWidth,f)):(c=Bb(f),Pa&&!E("9.50")&&(c=!1),c=c?f.documentElement:f.body,c=new H(c.clientWidth,c.clientHeight));b.right=Math.min(b.right,d+c.width);b.bottom=Math.min(b.bottom,g+c.height);return b.top>=0&&b.left>=0&&b.bottom>b.top&&b.right>b.left?b:p}
function $b(a){var b,c=L(a),d=Tb(a,"position"),g=C&&c.getBoxObjectFor&&!a.getBoundingClientRect&&d=="absolute"&&(b=c.getBoxObjectFor(a))&&(b.screenX<0||b.screenY<0),f=new F(0,0),h;b=c?c.nodeType==9?c:L(c):document;h=B&&!Qb(K(b))?b.body:b.documentElement;if(a==h)return f;if(a.getBoundingClientRect)b=Xb(a),a=Rb(K(c)),f.x=b.left+a.x,f.y=b.top+a.y;else if(c.getBoxObjectFor&&!g)b=c.getBoxObjectFor(a),a=c.getBoxObjectFor(h),f.x=b.screenX-a.screenX,f.y=b.screenY-a.screenY;else{b=a;do{f.x+=b.offsetLeft;f.y+=
b.offsetTop;b!=a&&(f.x+=b.clientLeft||0,f.y+=b.clientTop||0);if(D&&Tb(b,"position")=="fixed"){f.x+=c.body.scrollLeft;f.y+=c.body.scrollTop;break}b=b.offsetParent}while(b&&b!=a);if(Pa||D&&d=="absolute")f.y-=c.body.offsetTop;for(b=a;(b=Yb(b))&&b!=c.body&&b!=h;)if(f.x-=b.scrollLeft,!Pa||b.tagName!="TR")f.y-=b.scrollTop}return f}
function bc(a){var b=new F;if(a.nodeType==1)if(a.getBoundingClientRect)a=Xb(a),b.x=a.left,b.y=a.top;else{var c=Rb(K(a)),a=$b(a);b.x=a.x-c.x;b.y=a.y-c.y}else{var c=ha(a.td),d=a;a.targetTouches?d=a.targetTouches[0]:c&&a.v.targetTouches&&(d=a.v.targetTouches[0]);b.x=d.clientX;b.y=d.clientY}return b}function cc(a,b,c){b instanceof H?(c=b.height,b=b.width):c==i&&e(Error("missing height argument"));a.style.width=Vb(b,!0);a.style.height=Vb(c,!0)}
function Vb(a,b){typeof a=="number"&&(a=(b?Math.round(a):a)+"px");return a}
function dc(a){var b=Pa&&!E("10");if(Tb(a,"display")!="none")return b?new H(a.offsetWidth||a.clientWidth,a.offsetHeight||a.clientHeight):new H(a.offsetWidth,a.offsetHeight);var c=a.style,d=c.display,g=c.visibility,f=c.position;c.visibility="hidden";c.position="absolute";c.display="inline";b?(b=a.offsetWidth||a.clientWidth,a=a.offsetHeight||a.clientHeight):(b=a.offsetWidth,a=a.offsetHeight);c.display=d;c.position=f;c.visibility=g;return new H(b,a)}
function ec(a){var b=$b(a),a=dc(a);return new I(b.x,b.y,a.width,a.height)}function fc(a,b){a.style.display=b?"":"none"}function ac(a){return"rtl"==Tb(a,"direction")}var gc=C?"MozUserSelect":D?"WebkitUserSelect":p;function hc(a,b,c){c=!c?a.getElementsByTagName("*"):p;if(gc){if(b=b?"none":"",a.style[gc]=b,c)for(var a=0,d;d=c[a];a++)d.style[gc]=b}else if(B||Pa)if(b=b?"on":"",a.setAttribute("unselectable",b),c)for(a=0;d=c[a];a++)d.setAttribute("unselectable",b)}
function ic(a){return new H(a.offsetWidth,a.offsetHeight)}
function jc(a,b){var c=Qb(K(L(a)));if(B&&(!c||!E("8"))){var d=a.style;if(c){var c=kc(a),g=lc(a);d.pixelWidth=b.width-g.left-c.left-c.right-g.right;d.pixelHeight=b.height-g.top-c.top-c.bottom-g.bottom}else d.pixelWidth=b.width,d.pixelHeight=b.height}else d=a.style,C?d.MozBoxSizing="border-box":D?d.WebkitBoxSizing="border-box":Pa&&!E("9.50")?d.setProperty("box-sizing","border-box"):d.boxSizing="border-box",d.width=b.width+"px",d.height=b.height+"px"}
function mc(a){var b=L(a),c=B&&a.currentStyle;return c&&Qb(K(b))&&c.width!="auto"&&c.height!="auto"&&!c.boxSizing?(b=nc(a,c.width,"width","pixelWidth"),a=nc(a,c.height,"height","pixelHeight"),new H(b,a)):(c=ic(a),b=kc(a),a=lc(a),new H(c.width-a.left-b.left-b.right-a.right,c.height-a.top-b.top-b.bottom-a.bottom))}
function nc(a,b,c,d){if(/^\d+px?$/.test(b))return parseInt(b,10);else{var g=a.style[c],f=a.runtimeStyle[c];a.runtimeStyle[c]=a.currentStyle[c];a.style[c]=b;b=a.style[d];a.style[c]=g;a.runtimeStyle[c]=f;return b}}function oc(a,b){return nc(a,a.currentStyle?a.currentStyle[b]:p,"left","pixelLeft")}
function kc(a){if(B){var b=oc(a,"paddingLeft"),c=oc(a,"paddingRight"),d=oc(a,"paddingTop"),a=oc(a,"paddingBottom");return new hb(d,c,a,b)}else return b=N(a,"paddingLeft"),c=N(a,"paddingRight"),d=N(a,"paddingTop"),a=N(a,"paddingBottom"),new hb(parseFloat(d),parseFloat(c),parseFloat(a),parseFloat(b))}var pc={thin:2,medium:4,thick:6};
function qc(a,b){if((a.currentStyle?a.currentStyle[b+"Style"]:p)=="none")return 0;var c=a.currentStyle?a.currentStyle[b+"Width"]:p;return c in pc?pc[c]:nc(a,c,"left","pixelLeft")}function lc(a){if(B){var b=qc(a,"borderLeft"),c=qc(a,"borderRight"),d=qc(a,"borderTop"),a=qc(a,"borderBottom");return new hb(d,c,a,b)}else return b=N(a,"borderLeftWidth"),c=N(a,"borderRightWidth"),d=N(a,"borderTopWidth"),a=N(a,"borderBottomWidth"),new hb(parseFloat(d),parseFloat(c),parseFloat(a),parseFloat(b))};var rc;var sc=!B||E("9"),tc=B&&!E("8");function uc(){}uc.prototype.hc=!1;uc.prototype.I=function(){if(!this.hc)this.hc=!0,this.j()};uc.prototype.j=aa();function O(a,b){this.type=a;this.currentTarget=this.target=b}A(O,uc);t=O.prototype;t.j=function(){delete this.type;delete this.target;delete this.currentTarget};t.Ma=!1;t.xb=!0;t.stopPropagation=function(){this.Ma=!0};t.preventDefault=function(){this.xb=!1};function vc(a){a.preventDefault()};var wc=new Function("a","return a");function xc(a,b){a&&this.ia(a,b)}A(xc,O);var yc=[1,4,2];t=xc.prototype;t.target=p;t.relatedTarget=p;t.offsetX=0;t.offsetY=0;t.clientX=0;t.clientY=0;t.screenX=0;t.screenY=0;t.button=0;t.keyCode=0;t.charCode=0;t.ctrlKey=!1;t.altKey=!1;t.shiftKey=!1;t.metaKey=!1;t.Td=!1;t.v=p;
t.ia=function(a,b){var c=this.type=a.type;O.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(C)try{wc(d.nodeName)}catch(g){d=p}}else if(c=="mouseover")d=a.fromElement;else if(c=="mouseout")d=a.toElement;this.relatedTarget=d;this.offsetX=a.offsetX!==i?a.offsetX:a.layerX;this.offsetY=a.offsetY!==i?a.offsetY:a.layerY;this.clientX=a.clientX!==i?a.clientX:a.pageX;this.clientY=a.clientY!==i?a.clientY:a.pageY;this.screenX=a.screenX||0;this.screenY=a.screenY||
0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||(c=="keypress"?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.Td=Ia?a.metaKey:a.ctrlKey;this.state=a.state;this.v=a;delete this.xb;delete this.Ma};function zc(a){return(sc?a.v.button==0:a.type=="click"?!0:!!(a.v.button&yc[0]))&&!(D&&Ia&&a.ctrlKey)}
t.stopPropagation=function(){xc.a.stopPropagation.call(this);this.v.stopPropagation?this.v.stopPropagation():this.v.cancelBubble=!0};t.preventDefault=function(){xc.a.preventDefault.call(this);var a=this.v;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,tc)try{if(a.ctrlKey||a.keyCode>=112&&a.keyCode<=123)a.keyCode=-1}catch(b){}};t.td=r("v");t.j=function(){xc.a.j.call(this);this.relatedTarget=this.currentTarget=this.target=this.v=p};function Ac(){}var Bc=0;t=Ac.prototype;t.key=0;t.ab=!1;t.Hc=!1;t.ia=function(a,b,c,d,g,f){ha(a)?this.Tc=!0:a&&a.handleEvent&&ha(a.handleEvent)?this.Tc=!1:e(Error("Invalid listener argument"));this.Za=a;this.ad=b;this.src=c;this.type=d;this.capture=!!g;this.Pb=f;this.Hc=!1;this.key=++Bc;this.ab=!1};t.handleEvent=function(a){return this.Tc?this.Za.call(this.Pb||this.src,a):this.Za.handleEvent.call(this.Za,a)};var Cc,Dc=(Cc="ScriptEngine"in w&&w.ScriptEngine()=="JScript")?w.ScriptEngineMajorVersion()+"."+w.ScriptEngineMinorVersion()+"."+w.ScriptEngineBuildVersion():"0";function P(a,b){this.Wc=b;this.Ha=[];a>this.Wc&&e(Error("[goog.structs.SimplePool] Initial cannot be greater than max"));for(var c=0;c<a;c++)this.Ha.push(this.la?this.la():{})}A(P,uc);P.prototype.la=p;P.prototype.Lc=p;P.prototype.getObject=function(){return this.Ha.length?this.Ha.pop():this.la?this.la():{}};function Fc(a,b){a.Ha.length<a.Wc?a.Ha.push(b):Gc(a,b)}function Gc(a,b){if(a.Lc)a.Lc(b);else if(ia(b))if(ha(b.I))b.I();else for(var c in b)delete b[c]}
P.prototype.j=function(){P.a.j.call(this);for(var a=this.Ha;a.length;)Gc(this,a.pop());delete this.Ha};var Hc,Ic,Jc,Kc,Lc,Mc,Nc,Oc,Pc,Qc,Rc;
(function(){function a(){return{ba:0,Y:0}}function b(){return[]}function c(){function a(b){return h.call(a.src,a.key,b)}return a}function d(){return new Ac}function g(){return new xc}var f=Cc&&!(za(Dc,"5.7")>=0),h;Mc=function(a){h=a};if(f){Hc=function(){return j.getObject()};Ic=function(a){Fc(j,a)};Jc=function(){return k.getObject()};Kc=function(a){Fc(k,a)};Lc=function(){return l.getObject()};Nc=function(){Fc(l,c())};Oc=function(){return o.getObject()};Pc=function(a){Fc(o,a)};Qc=function(){return m.getObject()};
Rc=function(a){Fc(m,a)};var j=new P(0,600);j.la=a;var k=new P(0,600);k.la=b;var l=new P(0,600);l.la=c;var o=new P(0,600);o.la=d;var m=new P(0,600);m.la=g}else Hc=a,Ic=x,Jc=b,Kc=x,Lc=c,Nc=x,Oc=d,Pc=x,Qc=g,Rc=x})();var Sc={},Q={},Tc={},Uc={};
function R(a,b,c,d,g){if(b)if(ea(b)){for(var f=0;f<b.length;f++)R(a,b[f],c,d,g);return p}else{var d=!!d,h=Q;b in h||(h[b]=Hc());h=h[b];d in h||(h[d]=Hc(),h.ba++);var h=h[d],j=ja(a),k;h.Y++;if(h[j]){k=h[j];for(f=0;f<k.length;f++)if(h=k[f],h.Za==c&&h.Pb==g){if(h.ab)break;return k[f].key}}else k=h[j]=Jc(),h.ba++;f=Lc();f.src=a;h=Oc();h.ia(c,f,a,b,d,g);c=h.key;f.key=c;k.push(h);Sc[c]=h;Tc[j]||(Tc[j]=Jc());Tc[j].push(h);a.addEventListener?(a==w||!a.Kc)&&a.addEventListener(b,f,d):a.attachEvent(b in Uc?
Uc[b]:Uc[b]="on"+b,f);return c}else e(Error("Invalid event type"))}function Vc(a,b,c,d,g){if(ea(b))for(var f=0;f<b.length;f++)Vc(a,b[f],c,d,g);else if(d=!!d,a=Wc(a,b,d))for(f=0;f<a.length;f++)if(a[f].Za==c&&a[f].capture==d&&a[f].Pb==g){S(a[f].key);break}}
function S(a){if(Sc[a]){var b=Sc[a];if(!b.ab){var c=b.src,d=b.type,g=b.ad,f=b.capture;c.removeEventListener?(c==w||!c.Kc)&&c.removeEventListener(d,g,f):c.detachEvent&&c.detachEvent(d in Uc?Uc[d]:Uc[d]="on"+d,g);c=ja(c);g=Q[d][f][c];if(Tc[c]){var h=Tc[c];nb(h,b);h.length==0&&delete Tc[c]}b.ab=!0;g.Zc=!0;Xc(d,f,c,g);delete Sc[a]}}}
function Xc(a,b,c,d){if(!d.Ub&&d.Zc){for(var g=0,f=0;g<d.length;g++)if(d[g].ab){var h=d[g].ad;h.src=p;Nc(h);Pc(d[g])}else g!=f&&(d[f]=d[g]),f++;d.length=f;d.Zc=!1;f==0&&(Kc(d),delete Q[a][b][c],Q[a][b].ba--,Q[a][b].ba==0&&(Ic(Q[a][b]),delete Q[a][b],Q[a].ba--),Q[a].ba==0&&(Ic(Q[a]),delete Q[a]))}}
function Yc(a){var b,c=0,d=b==p;b=!!b;if(a==p)bb(Tc,function(a){for(var f=a.length-1;f>=0;f--){var g=a[f];if(d||b==g.capture)S(g.key),c++}});else if(a=ja(a),Tc[a])for(var a=Tc[a],g=a.length-1;g>=0;g--){var f=a[g];if(d||b==f.capture)S(f.key),c++}}function Wc(a,b,c){var d=Q;return b in d&&(d=d[b],c in d&&(d=d[c],a=ja(a),d[a]))?d[a]:p}
function Zc(a,b,c,d,g){var f=1,b=ja(b);if(a[b]){a.Y--;a=a[b];a.Ub?a.Ub++:a.Ub=1;try{for(var h=a.length,j=0;j<h;j++){var k=a[j];k&&!k.ab&&(f&=$c(k,g)!==!1)}}finally{a.Ub--,Xc(c,d,b,a)}}return Boolean(f)}function $c(a,b){var c=a.handleEvent(b);a.Hc&&S(a.key);return c}
Mc(function(a,b){if(!Sc[a])return!0;var c=Sc[a],d=c.type,g=Q;if(!(d in g))return!0;var g=g[d],f,h;rc===i&&(rc=B&&!w.addEventListener);if(rc){var j;if(!(j=b))a:{j="window.event".split(".");for(var k=w;f=j.shift();)if(k[f]!=p)k=k[f];else{j=p;break a}j=k}f=j;j=!0 in g;k=!1 in g;if(j){if(f.keyCode<0||f.returnValue!=i)return!0;a:{var l=!1;if(f.keyCode==0)try{f.keyCode=-1;break a}catch(o){l=!0}if(l||f.returnValue==i)f.returnValue=!0}}l=Qc();l.ia(f,this);f=!0;try{if(j){for(var m=Jc(),n=l.currentTarget;n;n=
n.parentNode)m.push(n);h=g[!0];h.Y=h.ba;for(var q=m.length-1;!l.Ma&&q>=0&&h.Y;q--)l.currentTarget=m[q],f&=Zc(h,m[q],d,!0,l);if(k){h=g[!1];h.Y=h.ba;for(q=0;!l.Ma&&q<m.length&&h.Y;q++)l.currentTarget=m[q],f&=Zc(h,m[q],d,!1,l)}}else f=$c(c,l)}finally{if(m)m.length=0,Kc(m);l.I();Rc(l)}return f}d=new xc(b,this);try{f=$c(c,d)}finally{d.I()}return f});function ad(a){this.Rc=a}A(ad,uc);var bd=new P(0,100),cd=[];ad.prototype.h=function(a,b,c,d,g){ea(b)||(cd[0]=b,b=cd);for(var f=0;f<b.length;f++){var h=R(a,b[f],c||this,d||!1,g||this.Rc||this);this.Q?this.Q[h]=!0:this.wa?(this.Q=bd.getObject(),this.Q[this.wa]=!0,this.wa=p,this.Q[h]=!0):this.wa=h}return this};
ad.prototype.aa=function(a,b,c,d,g){if(this.wa||this.Q)if(ea(b))for(var f=0;f<b.length;f++)this.aa(a,b[f],c,d,g);else{a:{c=c||this;g=g||this.Rc||this;d=!!d;if(a=Wc(a,b,d))for(b=0;b<a.length;b++)if(a[b].Za==c&&a[b].capture==d&&a[b].Pb==g){a=a[b];break a}a=p}if(a)if(a=a.key,S(a),this.Q)cb(this.Q,a);else if(this.wa==a)this.wa=p}return this};function dd(a){if(a.Q){for(var b in a.Q)S(b),delete a.Q[b];Fc(bd,a.Q);a.Q=p}else a.wa&&S(a.wa)}ad.prototype.j=function(){ad.a.j.call(this);dd(this)};
ad.prototype.handleEvent=function(){e(Error("EventHandler.handleEvent not implemented"))};function ed(){}y(ed);ed.prototype.Pd=0;ed.D();function gd(){}A(gd,uc);t=gd.prototype;t.Kc=!0;t.Wb=p;t.Ac=ba("Wb");t.addEventListener=function(a,b,c,d){R(this,a,b,c,d)};t.removeEventListener=function(a,b,c,d){Vc(this,a,b,c,d)};
t.dispatchEvent=function(a){var b=a.type||a,c=Q;if(b in c){if(z(a))a=new O(a,this);else if(a instanceof O)a.target=a.target||this;else{var d=a,a=new O(b,this);fb(a,d)}var d=1,g,c=c[b],b=!0 in c,f;if(b){g=[];for(f=this;f;f=f.Wb)g.push(f);f=c[!0];f.Y=f.ba;for(var h=g.length-1;!a.Ma&&h>=0&&f.Y;h--)a.currentTarget=g[h],d&=Zc(f,g[h],a.type,!0,a)&&a.xb!=!1}if(!1 in c)if(f=c[!1],f.Y=f.ba,b)for(h=0;!a.Ma&&h<g.length&&f.Y;h++)a.currentTarget=g[h],d&=Zc(f,g[h],a.type,!1,a)&&a.xb!=!1;else for(g=this;!a.Ma&&
g&&f.Y;g=g.Wb)a.currentTarget=g,d&=Zc(f,g,a.type,!1,a)&&a.xb!=!1;a=Boolean(d)}else a=!0;return a};t.j=function(){gd.a.j.call(this);Yc(this);this.Wb=p};function T(a){this.Ga=a||K();this.yb=id}A(T,gd);T.prototype.Id=ed.D();var id=p;function jd(a,b){switch(a){case 1:return b?"disable":"enable";case 2:return b?"highlight":"unhighlight";case 4:return b?"activate":"deactivate";case 8:return b?"select":"unselect";case 16:return b?"check":"uncheck";case 32:return b?"focus":"blur";case 64:return b?"open":"close"}e(Error("Invalid component state"))}t=T.prototype;t.Va=p;t.l=!1;t.i=p;t.yb=p;t.xc=p;t.J=p;t.H=p;t.N=p;t.jd=!1;
function kd(a){return a.Va||(a.Va=":"+(a.Id.Pd++).toString(36))}function ld(a,b){a.J&&a.J.N&&(cb(a.J.N,a.Va),db(a.J.N,b,a));a.Va=b}t.b=r("i");t.ga=function(){return this.Ta||(this.Ta=new ad(this))};function md(a,b){a==b&&e(Error("Unable to set parent component"));b&&a.J&&a.Va&&nd(a.J,a.Va)&&a.J!=b&&e(Error("Unable to set parent component"));a.J=b;T.a.Ac.call(a,b)}t.getParent=r("J");t.Ac=function(a){this.J&&this.J!=a&&e(Error("Method not supported"));T.a.Ac.call(this,a)};t.o=r("Ga");
t.d=function(){this.i=this.Ga.createElement("div")};t.bb=function(a){od(this,a)};function od(a,b,c){a.l&&e(Error("Component already rendered"));a.i||a.d();b?b.insertBefore(a.i,c||p):a.Ga.k.body.appendChild(a.i);(!a.J||a.J.l)&&a.A()}t.p=function(a){if(this.l)e(Error("Component already rendered"));else if(a&&this.C(a)){this.jd=!0;if(!this.Ga||this.Ga.k!=L(a))this.Ga=K(a);this.z(a);this.A()}else e(Error("Invalid element to decorate"))};t.C=s(!0);t.z=ba("i");
t.A=function(){this.l=!0;pd(this,function(a){!a.l&&a.b()&&a.A()})};t.fa=function(){pd(this,function(a){a.l&&a.fa()});this.Ta&&dd(this.Ta);this.l=!1};t.j=function(){T.a.j.call(this);this.l&&this.fa();this.Ta&&(this.Ta.I(),delete this.Ta);pd(this,function(a){a.I()});!this.jd&&this.i&&Hb(this.i);this.J=this.xc=this.i=this.N=this.H=p};t.Ca=function(a,b){this.ac(a,qd(this),b)};
t.ac=function(a,b,c){a.l&&(c||!this.l)&&e(Error("Component already rendered"));(b<0||b>qd(this))&&e(Error("Child component index out of bounds"));if(!this.N||!this.H)this.N={},this.H=[];a.getParent()==this?(this.N[kd(a)]=a,nb(this.H,a)):db(this.N,kd(a),a);md(a,this);qb(this.H,b,0,a);a.l&&this.l&&a.getParent()==this?(c=this.B(),c.insertBefore(a.b(),c.childNodes[b]||p)):c?(this.i||this.d(),b=U(this,b+1),od(a,this.B(),b?b.i:p)):this.l&&!a.l&&a.i&&a.A()};t.B=r("i");
function rd(a){if(a.yb==p)a.yb=ac(a.l?a.i:a.Ga.k.body);return a.yb}t.fb=function(a){this.l&&e(Error("Component already rendered"));this.yb=a};function qd(a){return a.H?a.H.length:0}function nd(a,b){return a.N&&b?(b in a.N?a.N[b]:i)||p:p}function U(a,b){return a.H?a.H[b]||p:p}function pd(a,b,c){a.H&&jb(a.H,b,c)}function sd(a,b){return a.H&&b?ib(a.H,b):-1}
t.removeChild=function(a,b){if(a){var c=z(a)?a:kd(a),a=nd(this,c);c&&a&&(cb(this.N,c),nb(this.H,a),b&&(a.fa(),a.i&&Hb(a.i)),md(a,p))}a||e(Error("Child is not in parent component"));return a};function td(a){T.call(this,this.de);this.name="Window";this.c=a;this.index=p}A(td,T);td.prototype.eb=ca.Fc;function ud(a){this.c=a;this.name="Layer";this.ca=this.canvas=p;this.$b=!0}t=ud.prototype;t.ia=function(){typeof this.c.da!=="number"&&e("current canvas window is unknown");this.canvas=vd(this.c.width,this.c.height);this.ca=this.canvas.getContext("2d");M(this.canvas,"position","absolute");var a=wd(this.c).ya.canvas;a.parentNode&&a.parentNode.insertBefore(this.canvas,a)};t.kb=ca.Fc;t.refresh=function(){this.clear();this.kb()};
t.clear=function(){(this.canvas===p||this.ca===p)&&e("canvas not initialized");this.ca.clearRect(0,0,this.c.width,this.c.height)};t.show=function(){this.$b=!0;fc(this.canvas,!0)};t.event=ca.Fc;function xd(a){ud.call(this,a);this.name="RasterLayer"}A(xd,ud);function yd(a){this.i=a;this.Vc=R(this.i,C?"DOMMouseScroll":"mousewheel",this)}A(yd,gd);
yd.prototype.handleEvent=function(a){var b=0,c=0,d=0,a=a.v;if(a.type=="mousewheel"){c=1;if(B||D&&(Ja||E("532.0")))c=40;d=D&&Ia&&-a.wheelDelta%c!=0?-a.wheelDelta:-a.wheelDelta/c;a.wheelDeltaX!==i?(b=D&&Ia&&-a.wheelDeltaX%c!=0?-a.wheelDeltaX:-a.wheelDeltaX/c,c=D&&Ia&&-a.wheelDeltaY%c!=0?-a.wheelDeltaY:-a.wheelDeltaY/c):c=d}else d=a.detail,d>100?d=3:d<-100&&(d=-3),a.axis!==i&&a.axis===a.HORIZONTAL_AXIS?b=d:c=d;ga(this.Xc)&&(b=Math.min(Math.max(b,-this.Xc),this.Xc));ga(this.Yc)&&(c=Math.min(Math.max(c,
-this.Yc),this.Yc));b=new zd(d,a,b,c);try{this.dispatchEvent(b)}finally{b.I()}};yd.prototype.j=function(){yd.a.j.call(this);S(this.Vc);delete this.Vc};function zd(a,b,c,d){b&&this.ia(b,i);this.type="mousewheel";this.detail=a;this.Ra=c;this.sa=d}A(zd,xc);function Ad(){this.name="Line";this.S=[]}Ad.prototype.Db=x;function Bd(){Ad.call(this);this.name="BezierAGG";this.na=[];this.$=[];this.G=Math.PI/2;this.Zb=0.75}A(Bd,Ad);function Cd(a,b){var c=a.S.length;a.S.push(b);a.na[c]=p;a.$[c]=p;c>=1&&(a.na[c-1]=p,a.$[c-1]=p);c>=2&&(a.na[c-2]=p,a.$[c-2]=p)}Ad.prototype.Db=function(a,b){a>=2&&(this.na[a-2]=p,this.$[a-2]=p);a>=1&&(this.na[a-1]=p,this.$[a-1]=p);a<this.$.length-1&&(this.na[a+1]=p,this.$[a+1]=p);this.na[a]=p;this.$[a]=p;this.S.splice(a,1,b)};
function Dd(a,b,c){var d=a.S,a=Ed(a,d,a.na),g=b.lineWidth,f=b.lineCap;b.beginPath();b.lineCap="round";b.moveTo(d[0].x,d[0].y);for(var h=1,j=d.length;h<j;h++){var k=d[h-1],l=d[h],o=a[h-1];switch(o.length){case 0:b.lineTo(l.x,l.y);break;case 2:b.bezierCurveTo(o[0].x,o[0].y,o[1].x,o[1].y,l.x,l.y);break;default:e("invalid control points")}if(!c)b.lineWidth=k.width+l.width,b.stroke(),b.beginPath(),b.moveTo(l.x,l.y)}if(c)b.lineWidth=c,b.stroke();b.lineWidth=g;b.lineCap=f}
Ad.prototype.kb=function(a){var b=this.S,c=Ed(this,b,this.na),d=[[],[]],g,f,h;a.beginPath();a.fillStyle="rgb(0,0,0)";for(var j=0,k=b.length-1;j<k;j++)if(g=b[j],f=b[j+1],h=c[j],!(Math.abs(g.x-f.x)<0.5&&Math.abs(g.y-f.y)<0.5))switch(h.length){case 2:var l=j,o=d,m=i,n=i,q=i,u=q=i,ua=u=i,Ka=i,u=typeof this.$[l]==="object"?this.$[l]:p;u===p?(q=Fd(this,g,h[0],h[1],f),m=q.Xa,n=q.Ya,ua=q.Mc,Ka=q.Nc,q=Ed(this,m,[]),u=Ed(this,n,[]),this.$[l]={Xa:m,Ya:n,pd:q,qd:u,Mc:ua,Nc:Ka}):(m=u.Xa,n=u.Ya,q=u.pd,u=u.qd);
g=0;for(f=m.length-1;g<f;g++){h=m[g];var l=n[g],ua=m[g+1],Ka=n[g+1],v=q[g],fd=u[g];v.length===2&&o[0].push({start:h,end:ua,ib:v});fd.length===2&&o[1].unshift({start:Ka,end:l,ib:[fd[1],fd[0]]})}}n=p;j=0;for(b=d.length;j<b;j++){c=d[j];k=0;for(o=c.length;k<o;k++){m=c[k];if(k===0)j===0?(n=d[b-1],n=n[n.length-1].end,q=Math.atan2(n.y-m.start.y,n.x-m.start.x),a.moveTo(n.x,n.y)):(n=n.end,q=Math.atan2(n.y-m.start.y,n.x-m.start.x)),a.arc((n.x+m.start.x)/2,(n.y+m.start.y)/2,Gd(n,m.start)/2,q,q+Math.PI,!0);a.bezierCurveTo(m.ib[0].x,
m.ib[0].y,m.ib[1].x,m.ib[1].y,m.end.x,m.end.y);n=m}}a.fill()};
function Ed(a,b,c){for(var d=0,g=b.length;d<g;d++){typeof c[d]!=="array"&&(c[d]=[]);var f=a,h=b,j=d,k=c,l=h.length,o=i,m=i,n=i,q=i,u=m=o=i,n=u=n=i;j<1||j>=l-1||(o=Gd(h[j-1],h[j]),m=Gd(h[j],h[j+1]),n={x:(h[j-1].x+h[j].x)/2,y:(h[j-1].y+h[j].y)/2},q={x:(h[j].x+h[j+1].x)/2,y:(h[j].y+h[j+1].y)/2},u=Gd(n,q),n=Math.atan2(q.y-n.y,q.x-n.x),u=o+m===0?0:u/(o+m),n=new V(Math.cos(n),Math.sin(n),p),o=new V(h[j].x-n.x*u*o*f.Zb,h[j].y-n.y*u*o*f.Zb,p),m=new V(h[j].x+n.x*u*m*f.Zb,h[j].y+n.y*u*m*f.Zb,p),j===1&&j===
l-2?(k[j-1]=Hd(h[j-1],o,h[j]),k[j]=Hd(h[j],m,h[j+1])):j===1?(k[j-1]=Hd(h[j-1],o,h[j]),k[j][0]=m):j===l-2?(k[j-1][1]=o,k[j]=Hd(h[j],m,h[j+1])):(k[j-1][1]=o,k[j][0]=m))}return c}
function Fd(a,b,c,d,g,f){var h=Math.atan2(c.y-b.y,c.x-b.x),j=Math.atan2(g.y-d.y,g.x-d.x),k,l,o,m=[],n=[];f||(f=0);if(f>8)return{Xa:m,Ya:n};f===0&&(m.push(new V(b.x+Math.cos(h+a.G)*b.width,b.y+Math.sin(h+a.G)*b.width,p)),n.push(new V(b.x+Math.cos(h-a.G)*b.width,b.y+Math.sin(h-a.G)*b.width,p)));if(f===0||Math.abs(j-h)>Math.PI*5/180)o=b.width+(g.width-b.width)*0.5,h=Id(b,c),c=Id(c,d),d=Id(d,g),k=Id(h,c),l=Id(c,d),c=Math.atan2(l.y-k.y,l.x-k.x),o=Id(k,l,o),b=Fd(a,b,h,k,o,f+1),Array.prototype.push.apply(m,
b.Xa),Array.prototype.push.apply(n,b.Ya),m.push(new V(o.x+Math.cos(c+a.G)*o.width,o.y+Math.sin(c+a.G)*o.width,p)),n.push(new V(o.x+Math.cos(c-a.G)*o.width,o.y+Math.sin(c-a.G)*o.width,p)),b=Fd(a,o,l,d,g,f+1),Array.prototype.push.apply(m,b.Xa),Array.prototype.push.apply(n,b.Ya);f===0&&(m.push(new V(g.x+Math.cos(j+a.G)*g.width,g.y+Math.sin(j+a.G)*g.width,p)),n.push(new V(g.x+Math.cos(j-a.G)*g.width,g.y+Math.sin(j-a.G)*g.width,p)));return{Xa:m,Ya:n,Mc:j+a.G,Nc:j-a.G}}
function Id(a,b,c){return new V(a.x+(b.x-a.x)*0.5,a.y+(b.y-a.y)*0.5,typeof c==="number"?c:p,!0)}function Hd(a,b,c){return[new V((a.x+b.x*2)/3,(a.y+b.y*2)/3,p),new V((c.x+b.x*2)/3,(c.y+b.y*2)/3,p)]}function Gd(a,b){return Math.sqrt(Math.pow(a.x-b.x,2)+Math.pow(a.y-b.y,2))};function V(a,b,c,d){this.name="Point";this.x=typeof a==="undefined"?0:a;this.y=typeof b==="undefined"?0:b;(isNaN(a)||isNaN(b))&&e("NaN error");this.width=p;if(typeof c==="number")d||(a=document.embeds["wacom-plugin"],c*=typeof a!=="object"&&typeof a!=="function"?1:a.isWacom?a.pointerType===2||a.pointerType===0?1:a.pressure:1),this.width=c};function Jd(a){ud.call(this,a);this.name="VectorLayer";this.od=this.mode=Kd;this.F=[];this.T=this.O=p;this.Kd=[];this.Tb=[];this.ce=this.Fb=this.Lb=p}A(Jd,ud);var Kd=0;t=Jd.prototype;
t.event=function(a){var b=this.canvas,c=this.ca,d=$b(a.target),g=a.v.pageX-d.x,d=a.v.pageY-d.y;(b===p||c===p)&&e("canvas not initialized");switch(a.type){case "mousemove":this.x=g;this.y=d;if(wd(this.c).jb)switch(this.mode){case Kd:g=this.F[this.O];d=new V(this.x,this.y,this.c.M[this.c.Bb].size);Cd(g,d);this.outline=!0;Ld(this);this.outline=!1;break;case 1:if(this.T!==p){var b=this.T,f=this.F[this.O],c=f.S[b.za].width;f.Db(b.za,new V(g,d,c,!0));Ld(this)}}else{c=p;b=typeof this.c.da==="number"?this.c.M[this.c.da].element:
this.canvas;switch(this.mode){case Kd:M(b,"cursor","default");break;case 1:a:{for(var c=this.ca,f=0,h=this.F.length;f<h;f++)for(var j=h-f-1,k=this.F[j].S,l=0,o=k.length;l<o;l++){var m=o-l-1,n=k[m];c.beginPath();c.arc(n.x|0,n.y|0,5,0,Math.PI*2,!1);if(c.isPointInPath(g,d)){c={tb:j,za:m};break a}}c=p}c!==p?M(b,"cursor","move"):M(b,"cursor","default")}this.T=c}break;case "mousedown":switch(this.mode){case Kd:this.save();f=new Bd;g=new V(g,d,this.c.M[this.c.Bb].size);this.O=this.F.length;this.F.push(f);
Cd(f,g);this.Fb=this.ca.getImageData(0,0,this.c.width,this.c.height);this.Lb=p;this.outline=!0;Ld(this);this.outline=!1;break;case 1:if(this.T!==p)b=this.T,f=this.F[b.tb],c=f.S[b.za].width,this.O=b.tb,f.Db(b.za,new V(g,d,c,!0)),Md(this,this.O),Ld(this)}break;case "mouseup":switch(this.mode){case 1:if(this.T!==p)b=this.T,f=this.F[this.O],c=f.S[b.za].width,f.Db(b.za,new V(g,d,c,!0)),Ld(this),this.pop(),this.O=p}break;case "mousewheel":switch(this.mode){case 1:if(this.T!==p)b=this.T,f=this.F[b.tb],g=
f.S[b.za],c=g.width,d=this.O,this.O=b.tb,a.sa<0&&(c+=1),a.sa>0&&(c-=1,c<0.1&&(c=0.1)),f.Db(b.za,new V(g.x,g.y,c,!0)),Md(this,this.O),Ld(this),this.O=d}}if(a.altKey)this.mode=1,Nd(this);else if(!wd(this.c).jb)this.mode=this.od,this.c.M[this.c.da].ya.ca.clearRect(0,0,this.c.width,this.c.height)};function Ld(a){a.restore();a.save();a.kb(a.O)}
function Md(a,b){var c=a.c.M[a.c.da].gd,d,g,f=vd(a.c.width,a.c.height).getContext("2d");for(d=0;d<b;d++)c.putImageData(a.Tb[d],0,0),f.drawImage(c.canvas,0,0);a.Fb=f.getImageData(0,0,a.c.width,a.c.height);f.clearRect(0,0,a.c.width,a.c.height);d=b+1;for(g=a.F.length;d<g;d++)c.putImageData(a.Tb[d],0,0),f.drawImage(c.canvas,0,0);a.Lb=f.getImageData(0,0,a.c.width,a.c.height)}
t.kb=function(a){var b=this.ca,c=this.c.M[this.c.da].gd;(this.canvas===p||b===p)&&e("canvas not initialized");if(typeof a==="number"){var d=this.F[a];c.clearRect(0,0,this.c.width,this.c.height);d.kb(c);this.Tb[a]=c.getImageData(0,0,this.c.width,this.c.height)}b.clearRect(0,0,this.c.width,this.c.height);this.Fb&&(c.putImageData(this.Fb,0,0),b.drawImage(c.canvas,0,0));c.putImageData(this.Tb[a],0,0);b.drawImage(c.canvas,0,0);this.Lb&&(c.putImageData(this.Lb,0,0),b.drawImage(c.canvas,0,0));switch(this.mode){case 1:Nd(this,
a)}};function Nd(a,b){var c=a.c.M[a.c.da].ya.ca;c.clearRect(0,0,a.c.width,a.c.height);c.strokeStyle="rgb(196,196,255)";if(typeof b==="number")Dd(a.F[b],c,1),Od(a,c,b);else{a.T&&Dd(a.F[a.T.tb],c,2);for(var d=0,g=a.F.length;d<g;d++)Od(a,c,d)}}function Od(a,b,c){a=a.F[c].S;b.beginPath();b.strokeStyle="rgb(0,0,255)";b.fillStyle="rgb(255,255,255)";for(var d=0,g=a.length;d<g;d++)c=a[d],b.moveTo(c.x+3,c.y),b.arc(c.x,c.y,3,0,7,!1);b.fill();b.stroke()}t.save=aa();t.restore=aa();t.pop=function(){this.Kd.pop()};function Pd(a,b,c,d){td.call(this,a);this.name="CanvasWindow";this.element=p;this.jb=!1;this.ja=[];this.ma=p;this.width=c?c:a.width;this.height=d?d:a.height;this.ya={};this.ya.canvas=vd(a.width,a.height);this.ya.ca=this.ya.canvas.getContext("2d");M(this.ya.canvas,"position","absolute");this.gd=vd(a.width,a.height).getContext("2d")}A(Pd,td);Pd.prototype.C=s(!1);
Pd.prototype.z=function(a){Pd.a.z.call(this,a);Fb(this.c.target,this.element);this.fc=document.createElement("div");M(this.fc,"position","relative");Fb(this.element,this.fc);Fb(this.fc,this.ya.canvas);this.eb()};Pd.prototype.d=function(){this.element=document.createElement("div");this.z(this.element)};
Pd.prototype.eb=function(){var a=this,b;b={mousemove:function(b){var d=a.ja[a.ma];d&&d.event(b)},mousedown:function(b){var d=a.ja[a.ma];a.jb=!0;d&&d.event(b)},mouseup:function(b){var d=a.jb,g=a.ja[a.ma];a.jb=!1;g&&d&&g.event(b)}};b.mouseout=function(c){var d=$b(a.element),g=c.pageX-d.x,d=c.pageY-d.y;if(!(g>=0&&g<a.element.width()&&d>=0&&d<a.element.height()))return c.type="mouseup",b[c.type](c)};b.mousewheel=function(b){var d=a.ja[a.ma];d&&d.event(b);b.preventDefault()};jb(["mousemove","mousedown",
"mouseup","mouseout","mousewheel"],function(a){var d=this.element;a==="mousewheel"&&(d=new yd(d));R(d,a,b[a])},this)};function Qd(a,b,c){this.target=a;this.handle=b||a;this.wc=c||new I(NaN,NaN,NaN,NaN);this.k=L(a);this.ea=new ad(this);R(this.handle,["touchstart","mousedown"],this.cd,!1,this)}A(Qd,gd);var Rd=B||C&&E("1.9.3");t=Qd.prototype;t.clientX=0;t.clientY=0;t.screenX=0;t.screenY=0;t.dd=0;t.ed=0;t.Ra=0;t.sa=0;t.U=!0;t.ta=!1;t.Sc=0;t.Od=0;t.Jd=!1;t.ga=r("ea");t.qa=ba("U");
t.j=function(){Qd.a.j.call(this);Vc(this.handle,["touchstart","mousedown"],this.cd,!1,this);this.ea.I();delete this.target;delete this.handle;delete this.ea};
t.cd=function(a){var b=a.type=="mousedown";if(this.U&&!this.ta&&(!b||zc(a))){Sd(a);if(this.Sc==0)if(Td(this,a),this.ta)a.preventDefault();else return;else a.preventDefault();var b=this.k,c=b.documentElement,d=!Rd;this.ea.h(b,["touchmove","mousemove"],this.Gd,d);this.ea.h(b,["touchend","mouseup"],this.Kb,d);Rd?(c.setCapture(!1),this.ea.h(c,"losecapture",this.Kb)):this.ea.h(b?b.parentWindow||b.defaultView:window,"blur",this.Kb);B&&this.Jd&&this.ea.h(b,"dragstart",vc);this.Xd&&this.ea.h(this.Xd,"scroll",
this.Qd,d);this.clientX=this.dd=a.clientX;this.clientY=this.ed=a.clientY;this.screenX=a.screenX;this.screenY=a.screenY;this.Ra=this.target.offsetLeft;this.sa=this.target.offsetTop;this.ub=Rb(K(this.k));this.Od=qa()}};function Td(a,b){if(a.dispatchEvent(new Ud("start",a,b.clientX,b.clientY,b))!==!1)a.ta=!0}
t.Kb=function(a,b){dd(this.ea);Rd&&this.k.releaseCapture();if(this.ta)Sd(a),this.ta=!1,this.dispatchEvent(new Ud("end",this,a.clientX,a.clientY,a,Vd(this,this.Ra),Wd(this,this.sa),b||a.type=="touchcancel"));(a.type=="touchend"||a.type=="touchcancel")&&a.preventDefault()};function Sd(a){var b=a.type;b=="touchstart"||b=="touchmove"?a.ia(a.v.targetTouches[0],a.currentTarget):(b=="touchend"||b=="touchcancel")&&a.ia(a.v.changedTouches[0],a.currentTarget)}
t.Gd=function(a){if(this.U){Sd(a);var b=a.clientX-this.clientX,c=a.clientY-this.clientY;this.clientX=a.clientX;this.clientY=a.clientY;this.screenX=a.screenX;this.screenY=a.screenY;if(!this.ta){var d=this.dd-this.clientX,g=this.ed-this.clientY;if(d*d+g*g>this.Sc&&(Td(this,a),!this.ta)){this.Kb(a);return}}c=Xd(this,b,c);b=c.x;c=c.y;this.ta&&this.dispatchEvent(new Ud("beforedrag",this,a.clientX,a.clientY,a,b,c))!==!1&&(Yd(this,a,b,c),a.preventDefault())}};
function Xd(a,b,c){var d=Rb(K(a.k));b+=d.x-a.ub.x;c+=d.y-a.ub.y;a.ub=d;a.Ra+=b;a.sa+=c;return new F(Vd(a,a.Ra),Wd(a,a.sa))}t.Qd=function(a){var b=Xd(this,0,0);a.clientX=this.ub.x-this.clientX;a.clientY=this.ub.y-this.clientY;Yd(this,a,b.x,b.y)};function Yd(a,b,c,d){a.target.style.left=c+"px";a.target.style.top=d+"px";a.dispatchEvent(new Ud("drag",a,b.clientX,b.clientY,b,c,d))}
function Vd(a,b){var c=a.wc,d=!isNaN(c.left)?c.left:p,c=!isNaN(c.width)?c.width:0;return Math.min(d!=p?d+c:Infinity,Math.max(d!=p?d:-Infinity,b))}function Wd(a,b){var c=a.wc,d=!isNaN(c.top)?c.top:p,c=!isNaN(c.height)?c.height:0;return Math.min(d!=p?d+c:Infinity,Math.max(d!=p?d:-Infinity,b))}function Ud(a,b,c,d,g,f,h,j){O.call(this,a);this.clientX=c;this.clientY=d;this.Zd=g;this.left=f!==i?f:b.Ra;this.top=h!==i?h:b.sa;this.ae=b;this.$d=!!j}A(Ud,O);function Zd(a,b,c,d){T.call(this,d);this.X=c;this.nb=a;this.Ca(a);this.zb=b;this.Ca(b)}A(Zd,T);t=Zd.prototype;t.Oa=p;t.q=p;t.cb=p;t.Ob=5;t.rc=p;t.bd=p;t.mb=p;t.Ib=!0;t.ha=p;t.d=function(){var a=this.o(),b=a.d("div","goog-splitpane-first-container"),c=a.d("div","goog-splitpane-second-container"),d=a.d("div","goog-splitpane-handle");this.i=a.d("div","goog-splitpane",b,c,d);this.q=b;this.cb=c;this.L=d;$d(this);ae(this)};
t.C=function(a){var b=Ab(document,p,"goog-splitpane-first-container",a)[0];if(!b)return!1;this.q=b;b=Ab(document,p,"goog-splitpane-second-container",a)[0];if(!b)return!1;this.cb=b;a=Ab(document,p,"goog-splitpane-handle",a)[0];if(!a)return!1;this.L=a;return!0};t.z=function(a){Zd.a.z.call(this,a);$d(this);a=ic(a);be(this,new H(a.width,a.height));ae(this)};
function ae(a){var b=a.o();a.nb.b()||a.nb.d();b.appendChild(a.q,a.nb.b());a.zb.b()||a.zb.d();b.appendChild(a.cb,a.zb.b());a.Oa=new Qd(a.L,a.L);a.q.style.position="absolute";a.cb.style.position="absolute";a=a.L.style;a.position="absolute";a.overflow="hidden";a.zIndex=2}t.A=function(){Zd.a.A.call(this);var a=this.b();if(Tb(a,"position")=="static")a.style.position="relative";this.ga().h(this.L,"dblclick",this.yd).h(this.Oa,"start",this.Ad).h(this.Oa,"drag",this.Bd).h(this.Oa,"end",this.zd);ce(this,this.rc)};
function de(a){return a.X=="vertical"}function $d(a){de(a)?(a.L.style.height=a.Ob+"px",J(a.L,"goog-splitpane-handle-vertical")):(a.L.style.width=a.Ob+"px",J(a.L,"goog-splitpane-handle-horizontal"))}
t.zc=function(a){if(this.X!=a&&(this.X=a,a=de(this),this.l))if(de(this)?wb(this.L,"goog-splitpane-handle-horizontal","goog-splitpane-handle-vertical"):wb(this.L,"goog-splitpane-handle-vertical","goog-splitpane-handle-horizontal"),ga(this.mb)){var b=ic(this.b());ce(this,this.mb*(a?b.height/b.width:b.width/b.height))}else ce(this)};function ee(a,b){Ub(a,b.left,b.top);jc(a,new H(Math.max(b.width,0),Math.max(b.height,0)))}
function ce(a,b){var c=ic(a.b()),d=de(a),g=ga(b)?b:ga(a.mb)?a.mb:Math.floor((d?c.height:c.width)/2);a.mb=g;var f,h,j,k,l,o,m;d?(j=d=c.width,k=a.Ob,h=c.height-g-k,f=c.width,m=0+g,o=0,l=m+k,c=0):(d=g,g=c.height,j=a.Ob,k=c.height,f=c.width-d-j,h=c.height,o=0+d,m=0,c=o+j,l=0);ee(a.q,new I(0,0,d,g));typeof a.nb.wb=="function"&&a.nb.wb(new H(d,g));ee(a.L,new I(o,m,j,k));ee(a.cb,new I(c,l,f,h));typeof a.zb.wb=="function"&&a.zb.wb(new H(f,h));a.dispatchEvent("change")}
function be(a,b){jc(a.b(),b);a.ha&&jc(a.ha,b);ce(a)}
t.Ad=function(){if(!this.ha){var a="position: relative";B&&(a+=";background-color: #000;filter: Alpha(Opacity=0)");this.ha=this.o().d("div",{style:a});this.o().appendChild(this.b(),this.ha)}this.ha.style.zIndex=1;jc(this.ha,ic(this.b()));var b=Wb(this.q),c=a=0,d=b.x,b=b.y,g=ic(this.q),f=mc(this.q),h=mc(this.cb);de(this)?(c=f.height+h.height,b+=g.height-f.height):(a=f.width+h.width,d+=g.width-f.width);this.Oa.wc=new I(d,b,a,c)||new I(NaN,NaN,NaN,NaN)};
t.Bd=function(a){this.Ib&&(de(this)?ce(this,a.top-Wb(this.q).y):ce(this,a.left-Wb(this.q).x))};t.zd=function(a){this.ha.style.zIndex=-1;this.Ib||(de(this)?ce(this,a.top-Wb(this.q).y):ce(this,a.left-Wb(this.q).x))};t.yd=function(){var a;a=this.q;var b=bc(this.L);a=bc(a);a=new F(b.x-a.x,b.y-a.y);var c=ic(this.q),d=mc(this.q);(b=de(this))?(c=c.height-d.height,a=a.y):(c=c.width-d.width,a=a.x);c==a?ce(this,this.bd):(this.bd=b?ic(this.q).height:ic(this.q).width,ce(this,c))};
t.j=function(){Zd.a.j.call(this);this.Oa.I();this.Oa=p;Hb(this.ha);this.ha=p};function fe(a){td.call(this,a);this.name="SizerWindow";this.canvas=this.element=p;this.height=this.width=0;this.size=5;this.sb=!1}A(fe,td);t=fe.prototype;t.C=s(!1);t.z=function(a){fe.a.z.call(this,a);J(a,"sizerwindow");this.canvas=vd(this.width,this.width);M(this.canvas,"border",1);Fb(this.element,this.canvas);this.eb()};
t.eb=function(){var a=this;R(this.canvas,"mousedown",function(b){a.sb=!0;a.size=ge(a,new F(b.offsetX,b.offsetY));a.refresh()});R(this.canvas,"mouseup",function(b){a.sb=!1;a.size=ge(a,new F(b.offsetX,b.offsetY));a.refresh()});R(this.canvas,"mousemove",function(b){if(a.sb)a.size=ge(a,new F(b.offsetX,b.offsetY)),a.refresh()});R(this.canvas,"mouseout",function(b){if(a.sb)a.sb=!1,a.size=ge(a,new F(b.offsetX,b.offsetY)),a.refresh()})};
function ge(a,b){var c=new F(a.width/2,a.height/2),d=c.x-b.x,c=c.y-b.y;return Math.sqrt(d*d+c*c)}t.d=function(){this.element=document.createElement("div");this.z(this.element);this.refresh()};t.wb=function(a){this.width=a.width;this.height=a.height;this.refresh()};
t.refresh=function(){var a=this.canvas.getContext("2d"),b=new F(this.width/2,this.height/2),c=this.size,d=this.width,g=this.height;this.canvas.width=d;this.canvas.height=g;a.beginPath();a.clearRect(0,0,d,g);a.lineWidth=1;a.strokeRect(0,0,d,g);a.moveTo(0,b.y);a.lineTo(d,b.y);a.moveTo(b.x,0);a.lineTo(b.x,g);a.stroke();a.beginPath();a.fillStyle="rgb(0,0,0)";a.moveTo(b.x+c,b.y);a.arc(b.x,b.y,c,0,7);a.fill()};function he(a,b){a.insertBefore(b,a.firstChild)}function ie(a,b){a.cc=a.cc||{};return typeof b==="undefined"?a.cc.layerIndex:a.cc.layerIndex=b}function je(){var a=document.body,b,c=a.style.overflow;a.style.overflow="hidden";b=a.clientWidth;a.style.overflow="scroll";b-=a.clientWidth;b||(b=a.offsetWidth-a.clientWidth);a.style.overflow=c;return b};function ke(a,b){a.setAttribute("role",b);a.fe=b}function le(a,b,c){a.setAttribute("aria-"+b,c)};function me(){}var ne;y(me);t=me.prototype;t.W=aa();t.d=function(a){return a.o().d("div",this.Sa(a).join(" "),a.Fa)};t.B=function(a){return a};t.lb=function(a,b,c){if(a=a.b?a.b():a)if(B&&!E("7")){var d=oe(ub(a),b);d.push(b);pa(c?J:vb,a).apply(p,d)}else c?J(a,b):vb(a,b)};t.C=s(!0);
t.p=function(a,b){b.id&&ld(a,b.id);var c=this.B(b);a.Fa=c&&c.firstChild?c.firstChild.nextSibling?pb(c.childNodes):c.firstChild:p;var d=0,g=this.g(),f=this.g(),h=!1,j=!1,c=!1,k=ub(b);jb(k,function(a){!h&&a==g?(h=!0,f==g&&(j=!0)):!j&&a==f?j=!0:d|=this.kc(a)},this);a.n=d;h||(k.push(g),f==g&&(j=!0));j||k.push(f);var l=a.V;l&&k.push.apply(k,l);if(B&&!E("7")){var o=oe(k);o.length>0&&(k.push.apply(k,o),c=!0)}if(!h||!j||l||c)b.className=k.join(" ");return b};
t.Wa=function(a){rd(a)&&this.fb(a.b(),!0);a.isEnabled()&&this.Aa(a,a.m)};t.Ab=function(a,b){hc(a,!b,!B&&!Pa)};t.fb=function(a,b){this.lb(a,this.g()+"-rtl",b)};t.ua=function(a){var b;return a.u&32&&(b=a.r())?Mb(b):!1};t.Aa=function(a,b){var c;if(a.u&32&&(c=a.r())){if(!b&&a.n&32){try{c.blur()}catch(d){}a.n&32&&a.Ja(p)}if(Mb(c)!=b)b?c.tabIndex=0:c.removeAttribute("tabIndex")}};t.Z=function(a,b){fc(a,b)};t.K=function(a,b,c){var d=a.b();if(d){var g=this.ob(b);g&&this.lb(a,g,c);this.gb(d,b,c)}};
t.gb=function(a,b,c){ne||(ne={1:"disabled",4:"pressed",8:"selected",16:"checked",64:"expanded"});(b=ne[b])&&le(a,b,c)};t.r=function(a){return a.b()};t.g=s("goog-control");t.Sa=function(a){var b=this.g(),c=[b],d=this.g();d!=b&&c.push(d);b=a.n;for(d=[];b;){var g=b&-b;d.push(this.ob(g));b&=~g}c.push.apply(c,d);(a=a.V)&&c.push.apply(c,a);B&&!E("7")&&c.push.apply(c,oe(c));return c};
function oe(a,b){var c=[];b&&(a=a.concat([b]));jb([],function(d){lb(d,pa(mb,a))&&(!b||mb(d,b))&&c.push(d.join("_"))});return c}t.ob=function(a){this.Hb||pe(this);return this.Hb[a]};t.kc=function(a){if(!this.fd){this.Hb||pe(this);var b=this.Hb,c={},d;for(d in b)c[b[d]]=d;this.fd=c}a=parseInt(this.fd[a],10);return isNaN(a)?0:a};function pe(a){var b=a.g();a.Hb={1:b+"-disabled",2:b+"-hover",4:b+"-active",8:b+"-selected",16:b+"-checked",32:b+"-focused",64:b+"-open"}};function qe(a,b){a||e(Error("Invalid class name "+a));ha(b)||e(Error("Invalid decorator function "+b));re[a]=b}var se={},re={};function te(a,b,c,d,g){if(!B&&(!D||!E("525")))return!0;if(Ia&&g)return ue(a);if(g&&!d)return!1;if(!c&&(b==17||b==18))return!1;if(B&&d&&b==a)return!1;switch(a){case 13:return!0;case 27:return!D}return ue(a)}
function ue(a){if(a>=48&&a<=57)return!0;if(a>=96&&a<=106)return!0;if(a>=65&&a<=90)return!0;if(D&&a==0)return!0;switch(a){case 32:case 63:case 107:case 109:case 110:case 111:case 186:case 189:case 187:case 188:case 190:case 191:case 192:case 222:case 219:case 220:case 221:return!0;default:return!1}};function ve(a,b){a&&we(this,a,b)}A(ve,gd);t=ve.prototype;t.i=p;t.Rb=p;t.tc=p;t.Sb=p;t.xa=-1;t.va=-1;
var xe={3:13,12:144,63232:38,63233:40,63234:37,63235:39,63236:112,63237:113,63238:114,63239:115,63240:116,63241:117,63242:118,63243:119,63244:120,63245:121,63246:122,63247:123,63248:44,63272:46,63273:36,63275:35,63276:33,63277:34,63289:144,63302:45},ye={Up:38,Down:40,Left:37,Right:39,Enter:13,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,"U+007F":46,Home:36,End:35,PageUp:33,PageDown:34,Insert:45},ze={61:187,59:186},Ae=B||D&&E("525");t=ve.prototype;
t.Cd=function(a){if(D&&(this.xa==17&&!a.ctrlKey||this.xa==18&&!a.altKey))this.va=this.xa=-1;Ae&&!te(a.keyCode,this.xa,a.shiftKey,a.ctrlKey,a.altKey)?this.handleEvent(a):this.va=C&&a.keyCode in ze?ze[a.keyCode]:a.keyCode};t.Dd=function(){this.va=this.xa=-1};
t.handleEvent=function(a){var b=a.v,c,d;B&&a.type=="keypress"?(c=this.va,d=c!=13&&c!=27?b.keyCode:0):D&&a.type=="keypress"?(c=this.va,d=b.charCode>=0&&b.charCode<63232&&ue(c)?b.charCode:0):Pa?(c=this.va,d=ue(c)?b.keyCode:0):(c=b.keyCode||this.va,d=b.charCode||0,Ia&&d==63&&!c&&(c=191));var g=c,f=b.keyIdentifier;c?c>=63232&&c in xe?g=xe[c]:c==25&&a.shiftKey&&(g=9):f&&f in ye&&(g=ye[f]);a=g==this.xa;this.xa=g;b=new Be(g,d,a,b);try{this.dispatchEvent(b)}finally{b.I()}};t.b=r("i");
function we(a,b,c){a.Sb&&a.detach();a.i=b;a.Rb=R(a.i,"keypress",a,c);a.tc=R(a.i,"keydown",a.Cd,c,a);a.Sb=R(a.i,"keyup",a.Dd,c,a)}t.detach=function(){if(this.Rb)S(this.Rb),S(this.tc),S(this.Sb),this.Sb=this.tc=this.Rb=p;this.i=p;this.va=this.xa=-1};t.j=function(){ve.a.j.call(this);this.detach()};function Be(a,b,c,d){d&&this.ia(d,i);this.type="key";this.keyCode=a;this.charCode=b;this.repeat=c}A(Be,xc);function W(a,b,c){T.call(this,c);if(!b){for(var b=this.constructor,d;b;){d=ja(b);if(d=se[d])break;b=b.a?b.a.constructor:p}b=d?ha(d.D)?d.D():new d:p}this.e=b;this.Fa=a}A(W,T);t=W.prototype;t.Fa=p;t.n=0;t.u=39;t.dc=255;t.Bc=0;t.m=!0;t.V=p;t.nc=!0;t.Eb=!1;function Ce(a,b){a.l&&b!=a.nc&&De(a,b);a.nc=b}t.r=function(){return this.e.r(this)};t.Mb=function(){return this.P||(this.P=new ve)};
t.lb=function(a,b){if(b){if(a)this.V?mb(this.V,a)||this.V.push(a):this.V=[a],this.e.lb(this,a,!0)}else if(a&&this.V){nb(this.V,a);if(this.V.length==0)this.V=p;this.e.lb(this,a,!1)}};t.d=function(){var a=this.e.d(this);this.i=a;var b=this.e.W();b&&ke(a,b);this.Eb||this.e.Ab(a,!1);this.m||this.e.Z(a,!1)};t.B=function(){return this.e.B(this.b())};t.C=function(a){return this.e.C(a)};
t.z=function(a){this.i=a=this.e.p(this,a);var b=this.e.W();b&&ke(a,b);this.Eb||this.e.Ab(a,!1);this.m=a.style.display!="none"};t.A=function(){W.a.A.call(this);this.e.Wa(this);if(this.u&-2&&(this.nc&&De(this,!0),this.u&32)){var a=this.r();if(a){var b=this.Mb();we(b,a);this.ga().h(b,"key",this.oa).h(a,"focus",this.Nb).h(a,"blur",this.Ja)}}};
function De(a,b){var c=a.ga(),d=a.b();b?(c.h(d,"mouseover",a.pc).h(d,"mousedown",a.Ka).h(d,"mouseup",a.La).h(d,"mouseout",a.oc),B&&c.h(d,"dblclick",a.Qc)):(c.aa(d,"mouseover",a.pc).aa(d,"mousedown",a.Ka).aa(d,"mouseup",a.La).aa(d,"mouseout",a.oc),B&&c.aa(d,"dblclick",a.Qc))}t.fa=function(){W.a.fa.call(this);this.P&&this.P.detach();this.m&&this.isEnabled()&&this.e.Aa(this,!1)};t.j=function(){W.a.j.call(this);this.P&&(this.P.I(),delete this.P);delete this.e;this.V=this.Fa=p};
function Ee(a,b){var c=a.Fa;return!c||z(c)?c:(c=ea(c)?kb(c,b).join(""):Nb(c))&&ra(c)}t.jc=function(){return Ee(this,Nb)};t.fb=function(a){W.a.fb.call(this,a);var b=this.b();b&&this.e.fb(b,a)};t.Ab=function(a){this.Eb=a;var b=this.b();b&&this.e.Ab(b,a)};t.Z=function(a,b){if(b||this.m!=a&&this.dispatchEvent(a?"show":"hide")){var c=this.b();c&&this.e.Z(c,a);this.isEnabled()&&this.e.Aa(this,a);this.m=a;return!0}return!1};t.isEnabled=function(){return!(this.n&1)};
t.qa=function(a){var b=this.getParent();if((!b||typeof b.isEnabled!="function"||b.isEnabled())&&Fe(this,1,!a))a||(this.setActive(!1),this.ka(!1)),this.m&&this.e.Aa(this,a),this.K(1,!a)};t.ka=function(a){Fe(this,2,a)&&this.K(2,a)};t.setActive=function(a){Fe(this,4,a)&&this.K(4,a)};t.t=function(a){Fe(this,64,a)&&this.K(64,a)};t.K=function(a,b){if(this.u&a&&b!=!!(this.n&a))this.e.K(this,a,b),this.n=b?this.n|a:this.n&~a};
function X(a,b,c){a.l&&a.n&b&&!c&&e(Error("Component already rendered"));!c&&a.n&b&&a.K(b,!1);a.u=c?a.u|b:a.u&~b}function Y(a,b){return!!(a.dc&b)&&!!(a.u&b)}function Fe(a,b,c){return!!(a.u&b)&&!!(a.n&b)!=c&&(!(a.Bc&b)||a.dispatchEvent(jd(b,c)))&&!a.hc}t.pc=function(a){(!a.relatedTarget||!Jb(this.b(),a.relatedTarget))&&this.dispatchEvent("enter")&&this.isEnabled()&&Y(this,2)&&this.ka(!0)};
t.oc=function(a){if((!a.relatedTarget||!Jb(this.b(),a.relatedTarget))&&this.dispatchEvent("leave"))Y(this,4)&&this.setActive(!1),Y(this,2)&&this.ka(!1)};t.Ka=function(a){this.isEnabled()&&(Y(this,2)&&this.ka(!0),zc(a)&&(Y(this,4)&&this.setActive(!0),this.e.ua(this)&&this.r().focus()));!this.Eb&&zc(a)&&a.preventDefault()};t.La=function(a){this.isEnabled()&&(Y(this,2)&&this.ka(!0),this.n&4&&this.$a(a)&&Y(this,4)&&this.setActive(!1))};t.Qc=function(a){this.isEnabled()&&this.$a(a)};
t.$a=function(a){if(Y(this,16)){var b=!(this.n&16);Fe(this,16,b)&&this.K(16,b)}Y(this,8)&&Fe(this,8,!0)&&this.K(8,!0);Y(this,64)&&this.t(!(this.n&64));b=new O("action",this);if(a)for(var c=["altKey","ctrlKey","metaKey","shiftKey","platformModifierKey"],d,g=0;d=c[g];g++)b[d]=a[d];return this.dispatchEvent(b)};t.Nb=function(){Y(this,32)&&Fe(this,32,!0)&&this.K(32,!0)};t.Ja=function(){Y(this,4)&&this.setActive(!1);Y(this,32)&&Fe(this,32,!1)&&this.K(32,!1)};
t.oa=function(a){return this.m&&this.isEnabled()&&this.Ua(a)?(a.preventDefault(),a.stopPropagation(),!0):!1};t.Ua=function(a){return a.keyCode==13&&this.$a(a)};ha(W)||e(Error("Invalid component class "+W));ha(me)||e(Error("Invalid renderer class "+me));var Ge=ja(W);se[Ge]=me;qe("goog-control",function(){return new W(p)});function He(){this.Jc=[]}A(He,me);y(He);function Ie(a,b){var c=a.Jc[b];if(!c){switch(b){case 0:c=a.g()+"-highlight";break;case 1:c=a.g()+"-checkbox";break;case 2:c=a.g()+"-content"}a.Jc[b]=c}return c}t=He.prototype;t.W=s("menuitem");t.d=function(a){var b=a.o().d("div",this.Sa(a).join(" "),Je(this,a.Fa,a.o()));Ke(this,a,b,!!(a.u&8)||!!(a.u&16));return b};t.B=function(a){return a&&a.firstChild};
t.p=function(a,b){var c=Ib(b),d=Ie(this,2);c&&c.className.indexOf(d)!=-1||b.appendChild(Je(this,b.childNodes,a.o()));mb(ub(b),"goog-option")&&(a.Xb(!0),this.Xb(a,b,!0));return He.a.p.call(this,a,b)};function Je(a,b,c){a=Ie(a,2);return c.d("div",a,b)}t.Xb=function(a,b,c){b&&(ke(b,c?"menuitemcheckbox":this.W()),Ke(this,a,b,c))};
function Ke(a,b,c,d){var g;if(g=a.B(c)){g=g.firstChild;var f=Ie(a,1);g=!!g&&!!g.className&&g.className.indexOf(f)!=-1}else g=!1;d!=g&&(d?J(c,"goog-option"):vb(c,"goog-option"),c=a.B(c),d?(a=Ie(a,1),c.insertBefore(b.o().d("div",a),c.firstChild||p)):c.removeChild(c.firstChild))}t.ob=function(a){switch(a){case 2:return Ie(this,0);case 16:case 8:return"goog-option-selected";default:return He.a.ob.call(this,a)}};
t.kc=function(a){var b=Ie(this,0);switch(a){case "goog-option-selected":return 16;case b:return 2;default:return He.a.kc.call(this,a)}};t.g=s("goog-menuitem");function Le(a,b,c,d){W.call(this,a,d||He.D(),c);this.Na(b)}A(Le,W);t=Le.prototype;t.Ia=function(){var a=this.xc;return a!=p?a:this.jc()};t.Na=ba("xc");t.Xb=function(a){X(this,16,a);var b=this.b();b&&this.e.Xb(this,b,a)};t.jc=function(){return Ee(this,function(a){return mb(ub(a),"goog-menuitem-accel")?"":Nb(a)})};t.La=function(a){var b=this.getParent();if(b){var c=b.$c;b.$c=p;if(b=c&&ga(a.clientX))b=new F(a.clientX,a.clientY),b=c==b?!0:!c||!b?!1:c.x==b.x&&c.y==b.y;if(b)return}Le.a.La.call(this,a)};
qe("goog-menuitem",function(){return new Le(p)});function Me(){}A(Me,me);y(Me);Me.prototype.d=function(a){return a.o().d("div",this.g())};Me.prototype.p=function(a,b){if(b.tagName=="HR"){var c=b,b=this.d(a);c.parentNode&&c.parentNode.insertBefore(b,c);Hb(c)}else J(b,this.g());return b};Me.prototype.g=s("goog-menuseparator");function Ne(){}A(Ne,Me);y(Ne);Ne.prototype.d=function(a){return a.o().d("div",this.g()+" goog-inline-block","\u00a0")};Ne.prototype.p=function(a,b){b=Ne.a.p.call(this,a,b);J(b,"goog-inline-block");return b};Ne.prototype.g=s("goog-toolbar-separator");function Oe(a,b){W.call(this,p,a||Me.D(),b);X(this,1,!1);X(this,2,!1);X(this,4,!1);X(this,32,!1);this.n=1}A(Oe,W);Oe.prototype.A=function(){Oe.a.A.call(this);ke(this.b(),"separator")};qe("goog-menuseparator",function(){return new Oe});function Pe(){}y(Pe);t=Pe.prototype;t.W=aa();function Qe(a,b){if(a)a.tabIndex=b?0:-1}t.d=function(a){return a.o().d("div",this.Sa(a).join(" "))};t.B=function(a){return a};t.C=function(a){return a.tagName=="DIV"};t.p=function(a,b){b.id&&ld(a,b.id);var c=this.g(),d=!1,g=ub(b);g&&jb(g,function(b){b==c?d=!0:b&&(b==c+"-disabled"?a.qa(!1):b==c+"-horizontal"?a.zc(Re):b==c+"-vertical"&&a.zc(Se))},this);d||J(b,c);Te(this,a,this.B(b));return b};
function Te(a,b,c){if(c)for(var d=c.firstChild,g;d&&d.parentNode==c;){g=d.nextSibling;if(d.nodeType==1){var f=a.pb(d);if(f)f.i=d,b.isEnabled()||f.qa(!1),b.Ca(f),f.p(d)}else(!d.nodeValue||ra(d.nodeValue)=="")&&c.removeChild(d);d=g}}t.pb=function(a){a:{for(var b=ub(a),c=0,d=b.length;c<d;c++)if(a=b[c]in re?re[b[c]]():p)break a;a=p}return a};t.Wa=function(a){a=a.b();hc(a,!0,C);if(B)a.hideFocus=!0;var b=this.W();b&&ke(a,b)};t.r=function(a){return a.b()};t.g=s("goog-container");
t.Sa=function(a){var b=this.g(),c=[b,a.X==Re?b+"-horizontal":b+"-vertical"];a.isEnabled()||c.push(b+"-disabled");return c};t.Oc=function(){return Se};function Z(a,b,c){T.call(this,c);this.e=b||Pe.D();this.X=a||this.e.Oc()}A(Z,T);var Re="horizontal",Se="vertical";t=Z.prototype;t.Uc=p;t.P=p;t.e=p;t.X=p;t.m=!0;t.U=!0;t.ic=!0;t.w=-1;t.s=p;t.pa=!1;t.md=!1;t.Sd=!0;t.ra=p;t.r=function(){return this.Uc||this.e.r(this)};t.Mb=function(){return this.P||(this.P=new ve(this.r()))};t.d=function(){this.i=this.e.d(this)};t.B=function(){return this.e.B(this.b())};t.C=function(a){return this.e.C(a)};
t.z=function(a){this.i=this.e.p(this,a);if(a.style.display=="none")this.m=!1};t.A=function(){Z.a.A.call(this);pd(this,function(a){a.l&&Ue(this,a)},this);var a=this.b();this.e.Wa(this);this.Z(this.m,!0);this.ga().h(this,"enter",this.lc).h(this,"highlight",this.mc).h(this,"unhighlight",this.qc).h(this,"open",this.Hd).h(this,"close",this.vd).h(a,"mousedown",this.Ka).h(L(a),"mouseup",this.xd).h(a,["mousedown","mouseup","mouseover","mouseout"],this.ud);this.ua()&&Ve(this,!0)};
function Ve(a,b){var c=a.ga(),d=a.r();b?c.h(d,"focus",a.Nb).h(d,"blur",a.Ja).h(a.Mb(),"key",a.oa):c.aa(d,"focus",a.Nb).aa(d,"blur",a.Ja).aa(a.Mb(),"key",a.oa)}t.fa=function(){We(this,-1);this.s&&this.s.t(!1);this.pa=!1;Z.a.fa.call(this)};t.j=function(){Z.a.j.call(this);if(this.P)this.P.I(),this.P=p;this.e=this.s=this.ra=p};t.lc=s(!0);
t.mc=function(a){var b=sd(this,a.target);if(b>-1&&b!=this.w){var c=U(this,this.w);c&&c.ka(!1);this.w=b;c=U(this,this.w);this.pa&&c.setActive(!0);this.Sd&&this.s&&c!=this.s&&(c.u&64?c.t(!0):this.s.t(!1))}le(this.b(),"activedescendant",a.target.b().id)};t.qc=function(a){if(a.target==U(this,this.w))this.w=-1;le(this.b(),"activedescendant","")};t.Hd=function(a){if((a=a.target)&&a!=this.s&&a.getParent()==this)this.s&&this.s.t(!1),this.s=a};t.vd=function(a){if(a.target==this.s)this.s=p};
t.Ka=function(a){if(this.U)this.pa=!0;var b=this.r();b&&Mb(b)?b.focus():a.preventDefault()};t.xd=function(){this.pa=!1};t.ud=function(a){var b;a:{b=a.target;if(this.ra)for(var c=this.b();b&&b!==c;){var d=b.id;if(d in this.ra){b=this.ra[d];break a}b=b.parentNode}b=p}if(b)switch(a.type){case "mousedown":b.Ka(a);break;case "mouseup":b.La(a);break;case "mouseover":b.pc(a);break;case "mouseout":b.oc(a)}};t.Nb=aa();t.Ja=function(){We(this,-1);this.pa=!1;this.s&&this.s.t(!1)};
t.oa=function(a){return this.isEnabled()&&this.m&&(qd(this)!=0||this.Uc)&&this.Ua(a)?(a.preventDefault(),a.stopPropagation(),!0):!1};
t.Ua=function(a){var b=U(this,this.w);if(b&&typeof b.oa=="function"&&b.oa(a))return!0;if(this.s&&this.s!=b&&typeof this.s.oa=="function"&&this.s.oa(a))return!0;if(a.shiftKey||a.ctrlKey||a.metaKey||a.altKey)return!1;switch(a.keyCode){case 27:if(this.ua())this.r().blur();else return!1;break;case 36:Xe(this);break;case 35:Ye(this);break;case 38:if(this.X==Se)Ze(this);else return!1;break;case 37:if(this.X==Re)rd(this)?$e(this):Ze(this);else return!1;break;case 40:if(this.X==Se)$e(this);else return!1;
break;case 39:if(this.X==Re)rd(this)?Ze(this):$e(this);else return!1;break;default:return!1}return!0};function Ue(a,b){var c=b.b(),c=c.id||(c.id=kd(b));if(!a.ra)a.ra={};a.ra[c]=b}t.Ca=function(a,b){Z.a.Ca.call(this,a,b)};t.ac=function(a,b,c){a.Bc|=2;a.Bc|=64;(this.ua()||!this.md)&&X(a,32,!1);Ce(a,!1);Z.a.ac.call(this,a,b,c);c&&this.l&&Ue(this,a);b<=this.w&&this.w++};
t.removeChild=function(a,b){if(a=z(a)?nd(this,a):a){var c=sd(this,a);c!=-1&&(c==this.w?a.ka(!1):c<this.w&&this.w--);(c=a.b())&&c.id&&cb(this.ra,c.id)}a=Z.a.removeChild.call(this,a,b);Ce(a,!0);return a};t.zc=function(a){this.b()&&e(Error("Component already rendered"));this.X=a};t.Z=function(a,b){if(b||this.m!=a&&this.dispatchEvent(a?"show":"hide")){this.m=a;var c=this.b();c&&(fc(c,a),this.ua()&&Qe(this.r(),this.U&&this.m),b||this.dispatchEvent(this.m?"aftershow":"afterhide"));return!0}return!1};
t.isEnabled=r("U");t.qa=function(a){if(this.U!=a&&this.dispatchEvent(a?"enable":"disable"))a?(this.U=!0,pd(this,function(a){a.kd?delete a.kd:a.qa(!0)})):(pd(this,function(a){a.isEnabled()?a.qa(!1):a.kd=!0}),this.pa=this.U=!1),this.ua()&&Qe(this.r(),a&&this.m)};t.ua=r("ic");t.Aa=function(a){a!=this.ic&&this.l&&Ve(this,a);this.ic=a;this.U&&this.m&&Qe(this.r(),a)};function We(a,b){var c=U(a,b);c?c.ka(!0):a.w>-1&&U(a,a.w).ka(!1)}t.ka=function(a){We(this,sd(this,a))};
function Xe(a){af(a,function(a,c){return(a+1)%c},qd(a)-1)}function Ye(a){af(a,function(a,c){a--;return a<0?c-1:a},0)}function $e(a){af(a,function(a,c){return(a+1)%c},a.w)}function Ze(a){af(a,function(a,c){a--;return a<0?c-1:a},a.w)}function af(a,b,c){for(var c=c<0?sd(a,a.s):c,d=qd(a),c=b.call(a,c,d),g=0;g<=d;){var f=U(a,c);if(f&&a.Ic(f)){We(a,c);break}g++;c=b.call(a,c,d)}}t.Ic=function(a){return a.m&&a.isEnabled()&&!!(a.u&2)};function bf(){}A(bf,Pe);y(bf);bf.prototype.W=s("toolbar");bf.prototype.pb=function(a){return a.tagName=="HR"?new Oe(Ne.D()):bf.a.pb.call(this,a)};bf.prototype.g=s("goog-toolbar");bf.prototype.Oc=function(){return Re};function cf(a,b,c){Z.call(this,b,a||bf.D(),c)}A(cf,Z);function df(a){Oe.call(this,Me.D(),a)}A(df,Oe);qe("goog-menuseparator",function(){return new Oe});function ef(){}A(ef,Pe);y(ef);t=ef.prototype;t.W=s("menu");t.C=function(a){return a.tagName=="UL"||ef.a.C.call(this,a)};t.pb=function(a){return a.tagName=="HR"?new Oe:ef.a.pb.call(this,a)};t.Ea=function(a,b){return Jb(a.b(),b)};t.g=s("goog-menu");t.Wa=function(a){ef.a.Wa.call(this,a);le(a.b(),"haspopup","true")};function ff(){}A(ff,me);y(ff);ff.prototype.g=s("goog-menuheader");function gf(a,b,c){W.call(this,a,c||ff.D(),b);X(this,1,!1);X(this,2,!1);X(this,4,!1);X(this,32,!1);this.n=1}A(gf,W);qe("goog-menuheader",function(){return new gf(p)});function hf(a,b){Z.call(this,Se,b||ef.D(),a);this.Aa(!1)}A(hf,Z);t=hf.prototype;t.bc=!0;t.nd=!1;t.g=function(){return this.e.g()};t.Ea=function(a){if(this.e.Ea(this,a))return!0;for(var b=0,c=qd(this);b<c;b++){var d=U(this,b);if(typeof d.Ea=="function"&&d.Ea(a))return!0}return!1};t.Z=function(a,b,c){(b=hf.a.Z.call(this,a,b))&&a&&this.l&&this.bc&&this.r().focus();this.$c=a&&c&&ga(c.clientX)?new F(c.clientX,c.clientY):p;return b};t.lc=function(a){this.bc&&this.r().focus();return hf.a.lc.call(this,a)};
t.Ic=function(a){return(this.nd||a.isEnabled())&&a.m&&!!(a.u&2)};t.z=function(a){var b=this.e,c;c=this.o();c=Ab(c.k,"div",b.g()+"-content",a);for(var d,g=0;d=c[g];g++)Te(b,this,d);hf.a.z.call(this,a)};function jf(a,b,c,d,g,f,h,j){var k,l=c.offsetParent;if(l){var o=l.tagName=="HTML"||l.tagName=="BODY";if(!o||Tb(l,"position")!="static")k=$b(l),o||(k=gb(k,new F(l.scrollLeft,l.scrollTop)))}l=ec(a);if(o=Zb(a)){var m=new I(o.left,o.top,o.right-o.left,o.bottom-o.top),o=Math.max(l.left,m.left),n=Math.min(l.left+l.width,m.left+m.width);if(o<=n){var q=Math.max(l.top,m.top),m=Math.min(l.top+l.height,m.top+m.height);if(q<=m)l.left=o,l.top=q,l.width=n-o,l.height=m-q}}o=K(a);q=K(c);if(o.k!=q.k){var n=o.k.body,
q=q.k.parentWindow||q.k.defaultView,m=new F(0,0),u=L(n)?L(n).parentWindow||L(n).defaultView:window,ua=n;do{var Ka=u==q?$b(ua):bc(ua);m.x+=Ka.x;m.y+=Ka.y}while(u&&u!=q&&(ua=u.frameElement)&&(u=u.parent));n=gb(m,$b(n));B&&!Qb(o)&&(n=gb(n,Rb(o)));l.left+=n.x;l.top+=n.y}a=(b&4&&ac(a)?b^2:b)&-5;b=new F(a&2?l.left+l.width:l.left,a&1?l.top+l.height:l.top);k&&(b=gb(b,k));g&&(b.x+=(a&2?-1:1)*g.x,b.y+=(a&1?-1:1)*g.y);var v;if(h&&(v=Zb(c))&&k)v.top=Math.max(0,v.top-k.y),v.right-=k.x,v.bottom-=k.y,v.left=Math.max(0,
v.left-k.x);a:{k=v;g=b.hb();v=0;a=(d&4&&ac(c)?d^2:d)&-5;d=dc(c);j=j?j.hb():d;if(f||a!=0)a&2?g.x-=j.width+(f?f.right:0):f&&(g.x+=f.left),a&1?g.y-=j.height+(f?f.bottom:0):f&&(g.y+=f.top);if(h){if(k){f=g;v=0;if(f.x<k.left&&h&1)f.x=k.left,v|=1;f.x<k.left&&f.x+j.width>k.right&&h&16&&(j.width-=f.x+j.width-k.right,v|=4);if(f.x+j.width>k.right&&h&1)f.x=Math.max(k.right-j.width,k.left),v|=1;h&2&&(v|=(f.x<k.left?16:0)|(f.x+j.width>k.right?32:0));if(f.y<k.top&&h&4)f.y=k.top,v|=2;f.y>=k.top&&f.y+j.height>k.bottom&&
h&32&&(j.height-=f.y+j.height-k.bottom,v|=8);if(f.y+j.height>k.bottom&&h&4)f.y=Math.max(k.bottom-j.height,k.top),v|=2;h&8&&(v|=(f.y<k.top?64:0)|(f.y+j.height>k.bottom?128:0));h=v}else h=256;v=h;if(v&496){c=v;break a}}Ub(c,g);d==j||(!d||!j?0:d.width==j.width&&d.height==j.height)||cc(c,j);c=v}return c};function kf(a,b){this.Qb=a||1;this.Cb=b||lf;this.ec=oa(this.Yd,this);this.uc=qa()}A(kf,gd);kf.prototype.enabled=!1;var lf=w.window;t=kf.prototype;t.R=p;t.Yd=function(){if(this.enabled){var a=qa()-this.uc;if(a>0&&a<this.Qb*0.8)this.R=this.Cb.setTimeout(this.ec,this.Qb-a);else if(this.dispatchEvent(mf),this.enabled)this.R=this.Cb.setTimeout(this.ec,this.Qb),this.uc=qa()}};t.start=function(){this.enabled=!0;if(!this.R)this.R=this.Cb.setTimeout(this.ec,this.Qb),this.uc=qa()};
t.stop=function(){this.enabled=!1;if(this.R)this.Cb.clearTimeout(this.R),this.R=p};t.j=function(){kf.a.j.call(this);this.stop();delete this.Cb};var mf="tick";function nf(){}nf.prototype.vb=aa();function of(a,b){this.element=a;this.Qa=b}A(of,nf);of.prototype.vb=function(a,b,c){jf(this.element,this.Qa,a,b,i,c)};function pf(a,b,c){of.call(this,a,b);this.ld=c}A(pf,of);pf.prototype.vb=function(a,b,c,d){var g=jf(this.element,this.Qa,a,b,p,c,10,d);if(g&496){var f=this.Qa,h=b;g&48&&(f^=2,h^=2);g&192&&(f^=1,h^=1);g=jf(this.element,f,a,h,p,c,10,d);g&496&&(this.ld?jf(this.element,this.Qa,a,b,p,c,5,d):jf(this.element,this.Qa,a,b,p,c,0,d))}};function qf(a,b,c,d){pf.call(this,a,b,c);this.Wd=d}A(qf,pf);qf.prototype.vb=function(a,b,c,d){this.Wd?jf(this.element,this.Qa,a,b,p,c,33,d):qf.a.vb.call(this,a,b,c,d)};function rf(){}A(rf,me);y(rf);t=rf.prototype;t.W=s("button");t.gb=function(a,b,c){b==16?le(a,"pressed",c):rf.a.gb.call(this,a,b,c)};t.d=function(a){var b=rf.a.d.call(this,a),c=a.qb();c&&this.Yb(b,c);(c=a.Ia())&&this.Na(b,c);a.u&16&&this.gb(b,16,!1);return b};t.p=function(a,b){var b=rf.a.p.call(this,a,b),c=this.Ia(b);a.Dc=c;a.Cc=this.qb(b);a.u&16&&this.gb(b,16,!1);return b};t.Ia=x;t.Na=x;t.qb=function(a){return a.title};t.Yb=function(a,b){if(a)a.title=b||""};t.g=s("goog-button");function sf(){}A(sf,rf);y(sf);t=sf.prototype;t.W=aa();t.d=function(a){Ce(a,!1);a.dc&=-256;X(a,32,!1);return a.o().d("button",{"class":this.Sa(a).join(" "),disabled:!a.isEnabled(),title:a.qb()||"",value:a.Ia()||""},a.jc()||"")};t.C=function(a){return a.tagName=="BUTTON"||a.tagName=="INPUT"&&(a.type=="button"||a.type=="submit"||a.type=="reset")};t.p=function(a,b){Ce(a,!1);a.dc&=-256;X(a,32,!1);b.disabled&&J(b,this.ob(1));return sf.a.p.call(this,a,b)};t.Wa=function(a){a.ga().h(a.b(),"click",a.$a)};
t.Ab=x;t.fb=x;t.ua=function(a){return a.isEnabled()};t.Aa=x;t.K=function(a,b,c){sf.a.K.call(this,a,b,c);if((a=a.b())&&b==1)a.disabled=c};t.Ia=function(a){return a.value};t.Na=function(a,b){if(a)a.value=b};t.gb=x;function tf(a,b,c){W.call(this,a,b||sf.D(),c)}A(tf,W);t=tf.prototype;t.Ia=r("Dc");t.Na=function(a){this.Dc=a;this.e.Na(this.b(),a)};t.qb=r("Cc");t.Yb=function(a){this.Cc=a;this.e.Yb(this.b(),a)};t.j=function(){tf.a.j.call(this);delete this.Dc;delete this.Cc};t.A=function(){tf.a.A.call(this);if(this.u&32){var a=this.r();a&&this.ga().h(a,"keyup",this.Ua)}};t.Ua=function(a){return a.keyCode==13&&a.type=="key"||a.keyCode==32&&a.type=="keyup"?this.$a(a):a.keyCode==32};qe("goog-button",function(){return new tf(p)});function uf(){}A(uf,rf);y(uf);t=uf.prototype;t.d=function(a){var b={"class":"goog-inline-block "+this.Sa(a).join(" "),title:a.qb()||""};return a.o().d("div",b,this.Jb(a.Fa,a.o()))};t.W=s("button");t.B=function(a){return a&&a.firstChild.firstChild};t.Jb=function(a,b){return b.d("div","goog-inline-block "+(this.g()+"-outer-box"),b.d("div","goog-inline-block "+(this.g()+"-inner-box"),a))};t.C=function(a){return a.tagName=="DIV"};
t.p=function(a,b){vf(b,!0);vf(b,!1);var c;a:{if((c=a.o().Pc(b))&&c.className.indexOf(this.g()+"-outer-box")!=-1)if((c=a.o().Pc(c))&&c.className.indexOf(this.g()+"-inner-box")!=-1){c=!0;break a}c=!1}c||b.appendChild(this.Jb(b.childNodes,a.o()));J(b,"goog-inline-block",this.g());return uf.a.p.call(this,a,b)};t.g=s("goog-custom-button");
function vf(a,b){if(a)for(var c=b?a.firstChild:a.lastChild,d;c&&c.parentNode==a;){d=b?c.nextSibling:c.previousSibling;if(c.nodeType==3){var g=c.nodeValue;if(ra(g)=="")a.removeChild(c);else{c.nodeValue=b?g.replace(/^[\s\xa0]+/,""):g.replace(/[\s\xa0]+$/,"");break}}else break;c=d}};function wf(){}A(wf,uf);y(wf);t=wf.prototype;t.B=function(a){a=wf.a.B.call(this,a&&a.firstChild);if(C&&a&&a.__goog_wrapper_div)a=a.firstChild;return a};t.p=function(a,b){var c=Ab(document,"*","goog-menu",b)[0];if(c){fc(c,!1);L(c).body.appendChild(c);var d=new hf;d.p(c);xf(a,d)}return wf.a.p.call(this,a,b)};t.Jb=function(a,b){return wf.a.Jb.call(this,[this.createCaption(a,b),b.d("div","goog-inline-block "+(this.g()+"-dropdown"),"\u00a0")],b)};
t.createCaption=function(a,b){return b.d("div","goog-inline-block "+(this.g()+"-caption"),a)};t.g=s("goog-menu-button");function $(a,b,c,d){tf.call(this,a,c||wf.D(),d);X(this,64,!0);b&&xf(this,b);this.R=new kf(500)}A($,tf);t=$.prototype;t.Gc=!0;t.yc=!1;t.sc=!1;t.Vd=!1;t.A=function(){$.a.A.call(this);this.f&&yf(this,this.f,!0);le(this.b(),"haspopup","true")};t.fa=function(){$.a.fa.call(this);if(this.f){this.t(!1);this.f.fa();yf(this,this.f,!1);var a=this.f.b();a&&Hb(a)}};t.j=function(){$.a.j.call(this);this.f&&(this.f.I(),delete this.f);delete this.Ud;this.R.I()};
t.Ka=function(a){$.a.Ka.call(this,a);if(this.n&4&&(this.t(!(this.n&64),a),this.f))this.f.pa=!!(this.n&64)};t.La=function(a){$.a.La.call(this,a);if(this.f&&!(this.n&4))this.f.pa=!1};t.$a=function(){this.setActive(!1);return!0};t.wd=function(a){this.f&&this.f.m&&!this.Ea(a.target)&&this.t(!1)};t.Ea=function(a){return a&&Jb(this.b(),a)||this.f&&this.f.Ea(a)||!1};
t.Ua=function(a){if(a.keyCode==32){if(a.preventDefault(),a.type!="keyup")return!1}else if(a.type!="key")return!1;if(this.f&&this.f.m){var b=this.f.oa(a);return a.keyCode==27?(this.t(!1),!0):b}return a.keyCode==40||a.keyCode==38||a.keyCode==32?(this.t(!0),!0):!1};t.Ed=function(){this.t(!1)};t.Fd=function(){this.n&4||this.t(!1)};t.Ja=function(a){this.sc||this.t(!1);$.a.Ja.call(this,a)};
function xf(a,b){var c=a.f;if(b!=c&&(c&&(a.t(!1),a.l&&yf(a,c,!1),delete a.f),b))a.f=b,md(b,a),b.Z(!1),c=a.sc,(b.bc=c)&&b.Aa(!0),a.l&&yf(a,b,!0)}t.Z=function(a,b){var c=$.a.Z.call(this,a,b);c&&!this.m&&this.t(!1);return c};t.qa=function(a){$.a.qa.call(this,a);this.isEnabled()||this.t(!1)};
t.t=function(a,b){$.a.t.call(this,a);if(this.f&&!!(this.n&64)==a){if(a)this.f.l||(this.Vd?this.f.bb(this.b().parentNode):this.f.bb()),this.Pa=Zb(this.b()),this.Da=ec(this.b()),zf(this),We(this.f,-1);else if(this.setActive(!1),this.f.pa=!1,this.Vb!=p){this.Vb=i;var c=this.f.b();c&&cc(c,"","")}this.f.Z(a,!1,b);var c=this.ga(),d=a?c.h:c.aa;d.call(c,Pb(this.o()),"mousedown",this.wd,!0);this.sc&&d.call(c,this.f,"blur",this.Fd);d.call(c,this.R,mf,this.Rd);a?this.R.start():this.R.stop()}};
function zf(a){if(a.f.l){var b=new qf(a.Ud||a.b(),a.Gc?5:7,!a.yc,a.yc),c=a.f.b();if(!a.f.m)c.style.visibility="hidden",fc(c,!0);if(!a.Vb&&a.yc)a.Vb=dc(c);b.vb(c,a.Gc?4:6,p,a.Vb);if(!a.f.m)fc(c,!1),c.style.visibility="visible"}}
t.Rd=function(){var a=ec(this.b()),b=Zb(this.b());if(!(this.Da==a||(!this.Da||!a?0:this.Da.left==a.left&&this.Da.width==a.width&&this.Da.top==a.top&&this.Da.height==a.height))||!(this.Pa==b||(!this.Pa||!b?0:this.Pa.top==b.top&&this.Pa.right==b.right&&this.Pa.bottom==b.bottom&&this.Pa.left==b.left)))this.Da=a,this.Pa=b,zf(this)};function yf(a,b,c){var d=a.ga(),c=c?d.h:d.aa;c.call(d,b,"action",a.Ed);c.call(d,b,"highlight",a.mc);c.call(d,b,"unhighlight",a.qc)}
t.mc=function(a){le(this.b(),"activedescendant",a.target.b().id)};t.qc=function(){U(this.f,this.f.w)||le(this.b(),"activedescendant","")};qe("goog-menu-button",function(){return new $(p)});function Af(){}A(Af,wf);y(Af);Af.prototype.g=s("goog-toolbar-menu-button");function Bf(a,b,c,d){$.call(this,a,b,c||Af.D(),d)}A(Bf,$);qe("goog-toolbar-menu-button",function(){return new Bf(p)});function Cf(a){td.call(this,a);this.name="LayerWindow";this.rb=this.element=p}A(Cf,td);Cf.prototype.C=s(!1);Cf.prototype.z=function(a){Cf.a.z.call(this,a);J(a,"layerwindow");J(a,this.c.gc+"layerWindow");this.toolbar=Df(this);this.rb=document.createElement("ul");J(this.rb,this.c.gc+"layerList");Fb(this.element,this.rb);this.refresh()};Cf.prototype.d=function(){this.element=document.createElement("div");this.z(this.element)};
function Df(a){var b=new cf,c=new hf,d=new $("Add Layer",c);d.Yb("Add Layer");jb([{label:"VectorLayer",type:"VectorLayer"},{label:"RasterLayer",type:"RasterLayer"}],function(b){var d;b?(d=new Le(b.label),d.Na(b.type),b.type!=="VectorLayer"&&d.qa(!1),R(d,"action",function(b){var c=wd(a.c),b=b.target.Ia(),d,f=c.ja.length;switch(b){case "VectorLayer":d=new Jd(c.c);break;case "RasterLayer":d=new xd(c.c);break;default:e("unsupported layer class")}d.ia();M(d.canvas,"border","1px solid black");c.ma=f;c.ja.push(d);
typeof c.c.rd==="number"&&c.c.M[c.c.rd].refresh();a.refresh()})):d=new df;c.Ca(d,!0)},a);b.Ca(d,!0);b.bb(a.element)}
Cf.prototype.refresh=function(){var a=this,b=wd(this.c),c;Gb(this.rb);if(b){c=b.ja;for(var d=0,g=c.length;d<g;d++){var f=document.createElement("li"),h=document.createElement("input"),j=c[d],k=j.name;Cb(h,{type:"checkbox",checked:j.$b});Fb(f,h);Fb(f,document.createTextNode(k+"("+d+")"));d===b.ma&&J(f,this.c.gc+"selectedLayer");ie(f,d);R(h,"click",function(){var c=ie(this.parentNode),c=b.ja[c];c.$b?(c.$b=!1,fc(c.canvas,!1)):c.show();a.refresh()});R(f,"click",function(){var c=ie(this);b.ma=c;a.refresh()});
he(this.rb,f)}}};function Ef(a){typeof a!=="object"&&(a={});this.target=p;this.gc="diceros-";this.width=a.width||1024;this.height=a.height||768;this.M=[];this.Bb=this.vc=this.da=p;this.Nd={}}Ef.prototype.bb=function(a){this.target=a;Ff(this);this.eb()};
function Ff(a){var b,c,d=a.height-je(),g=a.Nd;b=Gf(a,"LayerWindow");c=Gf(a,"CanvasWindow");sizer=Gf(a,"SizerWindow");g.Ba=new Zd(sizer,b,"vertical");g.Ba.rc=100;g.Ba.Ib=!0;g.Ba.wb=function(a){be(g.Ba,a.width)};g.Gb=new Zd(c,g.Ba,"horizontal");g.Gb.rc=a.width-200;g.Gb.Ib=!0;g.Gb.bb(a.target);be(g.Gb,new H(a.width,a.height));be(g.Ba,new H("100%",d));g.Ba.be=r("q");M(g.Ba.q,"overflow","hidden")}
function Gf(a,b){var c,d=a.M.length;switch(b){case "CanvasWindow":c=new Pd(a,0,a.width,a.height);a.da=d;a.da=d;break;case "LayerWindow":if(typeof a.vc!=="number")c=new Cf(a),a.vc=d;else return a.M[a.vc];break;case "SizerWindow":if(typeof a.Bb!=="number")c=new fe(a),a.Bb=d;else return a.M[a.Bb];break;default:e("unsupported window class")}a.M.push(c);return c}function wd(a){return a.M[a.da]}
function vd(a,b){var c=document.createElement("canvas");c.getContext||(window.Ec&&window.Ec.Ld?c=window.Ec.Ld(c):window.hd&&window.hd.canvas&&typeof window.hd.canvas.create==="function"?(document.createElement("div"),sb.ee(c),c=uu.canvas.create(a,b,"vml",uu.id("_canvas_dummy"))):e("canvas not supported"));c.width=a;c.height=b;return c}
Ef.prototype.eb=function(){var a=this;R(document,"keydown",function(b){var c=wd(a).ja[wd(a).ma];c&&c.event(b)});R(document,"keyup",function(b){var c=wd(a).ja[wd(a).ma];c&&c.event(b)})};function Hf(a,b){var c=z(a)?document.getElementById(a):a;typeof b!=="object"&&(b={});this.sd=new Ef(b);M(c,"width",(b.width||1024)+"px");M(c,"height",(b.height||768)+"px");this.sd.bb(c)}var If="Diceros.Main".split("."),Jf=w;!(If[0]in Jf)&&Jf.execScript&&Jf.execScript("var "+If[0]);for(var Kf;If.length&&(Kf=If.shift());)!If.length&&Hf!==i?Jf[Kf]=Hf:Jf=Jf[Kf]?Jf[Kf]:Jf[Kf]={};
